"""Markdown renderer for repo documentation."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from repo_docs_mcp.filesystem import safe_output_path
from repo_docs_mcp.models import AnalysisResult, DetectResult, RenderResult

GENERATED_HEADER = (
    "<!-- GENERATED by repo-docs-mcp. Do not edit manually unless you intend to overwrite generated output. -->\n"
)


def _join(items: list[str]) -> str:
    if not items:
        return "_None found_"
    return "\n".join(f"- {i}" for i in items)


def _make_anchor(text: str) -> str:
    """Convert a heading text to a markdown anchor."""
    return text.lower().strip().replace(" ", "-").replace("/", "").replace(".", "").replace("(", "").replace(")", "")


def _toc_for_headings(headings: list[str]) -> list[str]:
    """Generate a simple markdown TOC from heading texts."""
    lines = ["## Table of Contents", ""]
    for h in headings:
        lines.append(f"- [{h}](#{_make_anchor(h)})")
    lines.append("")
    return lines


def _maybe_errors_section(analysis: AnalysisResult) -> list[str]:
    if not analysis.errors:
        return []
    lines = [
        "## Errors",
        "",
        "The following non-fatal errors were encountered during analysis:",
        "",
    ]
    for err in analysis.errors[:30]:
        lines.append(f"- {err}")
    lines.append("")
    return lines


def render_project_overview(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate PROJECT_OVERVIEW.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "PROJECT_OVERVIEW.md"

    headings = [
        "Root Files",
        "Source Layout",
        "Entry Points",
    ]

    lines: list[str] = [
        GENERATED_HEADER,
        f"# Project Overview: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Detected types**: {', '.join(detect.project_types)}",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        "",
    ]

    has_langs = any(
        [
            analysis.python_modules,
            analysis.node_packages,
            analysis.dotnet_projects,
            analysis.rust_crates,
            analysis.go_modules,
            analysis.java_projects,
        ]
    )
    if has_langs:
        headings.insert(0, "Language Summaries")

    lines += _toc_for_headings(headings)

    lines += [
        "## Root Files",
        "",
        _join(analysis.root_files[:30]),
        "",
        "## Source Layout",
        "",
        _join(analysis.source_directories[:20]),
        "",
        "## Entry Points",
        "",
        _join(analysis.likely_entry_points[:20]),
        "",
    ]

    if analysis.python_modules:
        lines += [
            "### Python Summary",
            "",
            f"Modules scanned: {len(analysis.python_modules)}",
            "",
        ]
        entry_mods = [m for m in analysis.python_modules if m.is_entry_point][:10]
        if entry_mods:
            lines += ["#### Likely Python Entry Points", ""]
            for m in entry_mods:
                lines.append(f"- `{m.rel_path}`")
            lines.append("")
        classes: list[str] = []
        funcs: list[str] = []
        for m in analysis.python_modules:
            for c in m.classes:
                classes.append(f"{m.rel_path}::{c}")
            for f in m.functions:
                funcs.append(f"{m.rel_path}::{f}")
        lines += [f"Classes: {len(classes)}", f"Functions: {len(funcs)}", ""]

    if analysis.node_packages:
        pkg = analysis.node_packages[0]
        lines += ["### Node/JS Summary", ""]
        if pkg.name:
            lines.append(f"Package: `{pkg.name}`")
        if pkg.scripts:
            lines += ["#### Scripts", ""]
            for k, v in list(pkg.scripts.items())[:10]:
                lines.append(f"- `{k}`: `{v}`")
            lines.append("")
        lines.append(f"JS/TS files: {len(pkg.files)}")
        lines.append("")

    if analysis.dotnet_projects:
        lines += ["### .NET Summary", ""]
        for sol in analysis.dotnet_solutions:
            lines.append(f"- Solution: `{sol.name}` ({sol.rel_path})")
        for proj in analysis.dotnet_projects[:10]:
            lines.append(f"- Project: `{proj.name}` ({proj.rel_path})")
            if proj.target_frameworks:
                lines.append(f"  - Targets: {', '.join(proj.target_frameworks)}")
        lines.append("")

    if analysis.rust_crates:
        crate = analysis.rust_crates[0]
        lines += ["### Rust Summary", ""]
        if crate.name:
            lines.append(f"Crate: `{crate.name}`")
        lines.append(f"Modules: {len(crate.modules)}")
        if crate.entry_points:
            lines += ["#### Entry Points", ""]
            for ep in crate.entry_points:
                lines.append(f"- `{ep}`")
            lines.append("")
        if crate.dependencies:
            lines += ["#### Dependencies", ""]
            for dep in crate.dependencies[:15]:
                lines.append(f"- {dep}")
            lines.append("")

    if analysis.go_modules:
        mod = analysis.go_modules[0]
        lines += ["### Go Summary", ""]
        if mod.name:
            lines.append(f"Module: `{mod.name}`")
        lines.append(f"Packages: {len(mod.packages)}")
        if mod.entry_points:
            lines += ["#### Entry Points", ""]
            for ep in mod.entry_points:
                lines.append(f"- `{ep}`")
            lines.append("")
        if mod.dependencies:
            lines += ["#### Dependencies", ""]
            for dep in mod.dependencies[:15]:
                lines.append(f"- {dep}")
            lines.append("")

    if analysis.java_projects:
        java_proj = analysis.java_projects[0]
        lines += ["### Java Summary", ""]
        if java_proj.name:
            lines.append(f"Project: `{java_proj.name}`")
        if java_proj.build_tool:
            lines.append(f"Build tool: `{java_proj.build_tool}`")
        lines.append(f"Classes: {len(java_proj.classes)}")
        if java_proj.entry_points:
            lines += ["#### Entry Points", ""]
            for ep in java_proj.entry_points:
                lines.append(f"- `{ep}`")
            lines.append("")
        if java_proj.dependencies:
            lines += ["#### Dependencies", ""]
            for dep in java_proj.dependencies[:15]:
                lines.append(f"- {dep}")
            lines.append("")

    lines += _maybe_errors_section(analysis)
    lines += [
        "## Generic Notes",
        "",
        f"- Test directories: {', '.join(analysis.test_directories[:10]) or 'None identified'}",
        f"- Docs files: {len(analysis.docs_files)}",
        f"- Config files: {len(analysis.config_files)}",
        "",
        "---",
        "*This file was generated by repo-docs-mcp and may be regenerated.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )


def render_repo_map(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate REPO_MAP.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "REPO_MAP.md"

    lines: list[str] = [
        GENERATED_HEADER,
        f"# Repository Map: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Directory Tree",
        "",
        "```",
    ]
    lines += analysis.directory_tree[:200]
    lines += [
        "```",
        "",
        "## Important Config Files",
        "",
        _join(analysis.config_files[:30]),
        "",
        "## Likely Entry Points",
        "",
        _join(analysis.likely_entry_points[:20]),
        "",
        "## Test Directories",
        "",
        _join(analysis.test_directories[:20]),
        "",
        "## Docs Directories",
        "",
        _join(analysis.docs_files[:20]),
        "",
        "---",
        "*Generated by repo-docs-mcp.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )


def render_architecture_summary(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate ARCHITECTURE_SUMMARY.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "ARCHITECTURE_SUMMARY.md"

    headings = [
        "Detected Stacks",
        "Major Source Directories",
        "Likely Runtime Entry Points",
        "Testing Layout",
        "Packaging / Build System",
        "Documentation State",
        "Risks / Unknowns",
    ]

    lines: list[str] = [
        GENERATED_HEADER,
        f"# Architecture Summary: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        "",
    ]

    if analysis.errors:
        headings.insert(0, "Errors")

    lines += _toc_for_headings(headings)
    lines += _maybe_errors_section(analysis)

    lines += [
        "## Detected Stacks",
        "",
        _join(detect.project_types),
        "",
        "## Major Source Directories",
        "",
        _join(analysis.source_directories[:20]),
        "",
        "## Likely Runtime Entry Points",
        "",
        _join(analysis.likely_entry_points[:20]),
        "",
        "## Testing Layout",
        "",
        _join(analysis.test_directories[:20]),
        "",
        "## Packaging / Build System",
        "",
    ]

    if "python" in detect.project_types:
        lines.append("- Python project detected (look for `pyproject.toml`, `setup.py`)")
    if "node" in detect.project_types:
        lines.append("- Node project detected (look for `package.json`, build scripts)")
    if "dotnet" in detect.project_types:
        lines.append("- .NET project detected (look for `.sln`, `.csproj`)")
    if "rust" in detect.project_types:
        lines.append("- Rust project detected (look for `Cargo.toml`)")
    if "go" in detect.project_types:
        lines.append("- Go project detected (look for `go.mod`)")
    if "java" in detect.project_types:
        lines.append("- Java project detected (look for `pom.xml`, `build.gradle`)")
    lines.append("")

    lines += [
        "## Documentation State",
        "",
        f"- README: {'Yes' if any('readme' in f.lower() for f in analysis.root_files) else 'Not obvious'}",
        f"- Docs files: {len(analysis.docs_files)}",
        "",
        "## Risks / Unknowns",
        "",
    ]

    if not analysis.likely_entry_points:
        lines.append("- No clear entry points were identified automatically.")
    if not analysis.test_directories:
        lines.append("- No test directories were identified automatically.")
    if not analysis.config_files:
        lines.append("- No obvious config files found.")
    if len(analysis.root_files) < 3:
        lines.append("- Repository root appears sparse; may be a monorepo subdirectory or incomplete checkout.")
    if analysis.errors:
        lines.append("- Some files could not be parsed; see analysis errors.")
    if not any(
        [
            "python" in detect.project_types,
            "node" in detect.project_types,
            "dotnet" in detect.project_types,
            "rust" in detect.project_types,
            "go" in detect.project_types,
            "java" in detect.project_types,
        ]
    ):
        lines.append("- No mainstream stack markers found; architecture inference is limited.")

    lines += [
        "",
        "---",
        "*This analysis is based purely on static inspection. It may miss runtime architecture or cloud infra.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )
