"""Mermaid diagram renderer."""

from __future__ import annotations

import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from repo_docs_mcp.filesystem import safe_output_path
from repo_docs_mcp.models import AnalysisResult, DetectResult, RenderResult

GENERATED_HEADER = (
    "<!-- GENERATED by repo-docs-mcp. Do not edit manually unless you intend to overwrite generated output. -->\n"
)


def _sanitize_mermaid_id(name: str) -> str:
    """Sanitize a string for use as a Mermaid node ID."""
    sanitized = "".join(c if c.isalnum() or c in "_-" else "_" for c in name)
    if sanitized and sanitized[0].isdigit():
        sanitized = "_" + sanitized
    if not sanitized:
        sanitized = "_"
    return sanitized[:60]


def render_dependency_graph(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate Mermaid dependency graph files."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    mmd_path = out / "DEPENDENCY_GRAPH.mmd"
    md_path = out / "DEPENDENCY_GRAPH.md"

    lines: list[str] = [
        "graph TD",
    ]
    nodes: set[str] = set()
    edges: set[tuple[str, str]] = set()
    external: set[str] = set()

    # Python internal imports
    if analysis.python_modules:
        for mod in analysis.python_modules:
            mod_id = _sanitize_mermaid_id(mod.module_name or mod.rel_path)
            if mod_id not in nodes:
                nodes.add(mod_id)
                lines.append(f'    {mod_id}["{mod.rel_path}"]')
            for imp in mod.internal_imports:
                imp_id = _sanitize_mermaid_id(imp)
                if imp_id not in nodes:
                    nodes.add(imp_id)
                    lines.append(f'    {imp_id}["{imp}"]')
                edges.add((mod_id, imp_id))
            for imp in mod.imports:
                if imp not in mod.internal_imports:
                    first = imp.split(".")[0]
                    external.add(first)

    # Node import edges
    if analysis.node_packages:
        pkg = analysis.node_packages[0]
        for src, target in pkg.import_edges:
            src_id = _sanitize_mermaid_id(Path(src).name)
            if target.startswith(".") or "/" in target:
                tgt_id = _sanitize_mermaid_id(target)
                if src_id not in nodes:
                    nodes.add(src_id)
                    lines.append(f'    {src_id}["{src}"]')
                if tgt_id not in nodes:
                    nodes.add(tgt_id)
                    lines.append(f'    {tgt_id}["{target}"]')
                edges.add((src_id, tgt_id))
            else:
                external.add(target.split("/")[-1])

    # .NET project references
    if analysis.dotnet_projects:
        for proj in analysis.dotnet_projects:
            proj_id = _sanitize_mermaid_id(proj.name)
            if proj_id not in nodes:
                nodes.add(proj_id)
                lines.append(f'    {proj_id}["{proj.name}"]')
            for ref in proj.project_refs:
                ref_name = Path(ref).stem
                ref_id = _sanitize_mermaid_id(ref_name)
                if ref_id not in nodes:
                    nodes.add(ref_id)
                    lines.append(f'    {ref_id}["{ref_name}"]')
                edges.add((proj_id, ref_id))
        for sol in analysis.dotnet_solutions:
            sol_id = _sanitize_mermaid_id(sol.name)
            if sol_id not in nodes:
                nodes.add(sol_id)
                lines.append(f'    {sol_id}["{sol.name} (sln)"]')
            for p in sol.projects:
                p_name = Path(p).stem
                p_id = _sanitize_mermaid_id(p_name)
                if p_id not in nodes:
                    nodes.add(p_id)
                    lines.append(f'    {p_id}["{p_name}"]')
                edges.add((sol_id, p_id))

    for edge in edges:
        lines.append(f"    {edge[0]} --> {edge[1]}")

    mmd_content = "\n".join(lines)

    md_lines: list[str] = [
        GENERATED_HEADER,
        f"# Dependency Graph: {Path(repo_path).resolve().name}",
        "",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Graph",
        "",
        "```mermaid",
    ]
    md_lines += lines
    md_lines += [
        "```",
        "",
        "## External Dependencies",
        "",
    ]
    if external:
        for dep in sorted(external)[:30]:
            md_lines.append(f"- {dep}")
    else:
        md_lines.append("_No external dependencies identified._")
    md_lines += [
        "",
        "---",
        "*Generated by repo-docs-mcp.*",
        "",
    ]

    mmd_path.write_text(GENERATED_HEADER + mmd_content + "\n", encoding="utf-8")
    md_path.write_text("\n".join(md_lines) + "\n", encoding="utf-8")

    written = [str(mmd_path), str(md_path)]

    # Optional: generate PNG/SVG if mmdc is available
    if shutil.which("mmdc"):
        for fmt in ("png", "svg"):
            out_path = out / f"DEPENDENCY_GRAPH.{fmt}"
            try:
                subprocess.run(
                    ["mmdc", "-i", str(mmd_path), "-o", str(out_path), "-b", "transparent"],
                    capture_output=True,
                    timeout=60,
                    check=True,
                )
                written.append(str(out_path))
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
                pass

    return RenderResult(
        ok=True,
        written=written,
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )
