"""Markdown renderer for repo documentation."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from context_crafter_mcp import __version__
from context_crafter_mcp.filesystem import safe_output_path
from context_crafter_mcp.models import (
    AnalysisResult,
    DetectResult,
    EvidenceKind,
    RenderResult,
    get_profile_limit,
)
from context_crafter_mcp.ranking import classify_path, score_path, PathCategory
from context_crafter_mcp.redaction import write_redacted_text

GENERATED_HEADER = (
    f"<!-- GENERATED by context-crafter-mcp v{__version__}. "
    "Do not edit manually unless you intend to overwrite generated output. -->\n"
)


def _join(items: list[str]) -> str:
    if not items:
        return "_None found_"
    return "\n".join(f"- {i}" for i in items)


def _safe_inline_code(text: str) -> str:
    """Wrap text in inline code, escaping backticks by using double backticks."""
    if not text:
        return "``"
    if "`" in text:
        return f"``{text}``"
    return f"`{text}`"


@dataclass(frozen=True)
class CommandHint:
    """A statically inferred command with evidence and confidence."""

    command: str
    purpose: str
    confidence: str
    evidence: str


def _render_metadata_block(repo_path: str, analysis: AnalysisResult, generated_at: str) -> list[str]:
    """Render a consistent metadata block for markdown files."""
    lines: list[str] = [
        f"- **Generated by**: context-crafter-mcp v{__version__}",
        f"- **Generated at**: {generated_at}",
        f"- **Source repo**: {Path(repo_path).resolve().name}",
    ]
    ss = analysis.scan_summary
    if ss.git_commit:
        lines.append(f"- **Git commit**: {ss.git_commit}")
    lines.append(f"- **Profile**: {analysis.profile}")
    lines.append(
        f"- **Scanner**: max_files={ss.max_files}, max_depth={ss.max_depth}, max_file_bytes={ss.max_file_bytes}"
    )
    lines.append("")
    return lines


def _has_file(analysis: AnalysisResult, name: str) -> bool:
    """Return true when a scanned file/root file has the given basename."""
    target = name.lower()
    candidates = analysis.root_files + analysis.config_files
    return any(Path(candidate).name.lower() == target for candidate in candidates)


def _append_command(hints: list[CommandHint], seen: set[str], hint: CommandHint) -> None:
    if hint.command in seen:
        return
    seen.add(hint.command)
    hints.append(hint)


def _collect_command_hints(analysis: AnalysisResult) -> list[CommandHint]:
    """Collect likely project commands from static markers and parsed package metadata."""
    hints: list[CommandHint] = []
    seen: set[str] = set()

    if _has_file(analysis, "pyproject.toml"):
        _append_command(
            hints,
            seen,
            CommandHint(
                "uv sync --extra dev",
                "Install Python project and development dependencies",
                "medium",
                "pyproject.toml",
            ),
        )
        if analysis.test_directories:
            _append_command(
                hints,
                seen,
                CommandHint(
                    "uv run python -m pytest -q",
                    "Run Python tests",
                    "medium",
                    "pyproject.toml and test directory",
                ),
            )
    elif _has_file(analysis, "requirements.txt"):
        _append_command(
            hints,
            seen,
            CommandHint(
                "python -m pip install -r requirements.txt",
                "Install Python dependencies",
                "medium",
                "requirements.txt",
            ),
        )
        if analysis.test_directories:
            _append_command(
                hints,
                seen,
                CommandHint("python -m pytest -q", "Run Python tests", "low", "requirements.txt and test directory"),
            )

    for pkg in analysis.node_packages:
        if pkg.dependencies or pkg.dev_dependencies or _has_file(analysis, "package-lock.json"):
            _append_command(
                hints,
                seen,
                CommandHint("npm install", "Install Node dependencies", "medium", pkg.rel_path or "package.json"),
            )
        for script in ("test", "lint", "typecheck", "build", "start", "dev"):
            if script in pkg.scripts:
                _append_command(
                    hints,
                    seen,
                    CommandHint(
                        f"npm run {script}",
                        f"Run Node `{script}` script",
                        "high",
                        f"{pkg.rel_path or 'package.json'} scripts.{script}",
                    ),
                )

    if analysis.go_modules:
        _append_command(hints, seen, CommandHint("go test ./...", "Run Go tests", "medium", "go.mod"))
        _append_command(hints, seen, CommandHint("go build ./...", "Build Go packages", "medium", "go.mod"))

    if analysis.rust_crates:
        _append_command(hints, seen, CommandHint("cargo test", "Run Rust tests", "medium", "Cargo.toml"))
        _append_command(hints, seen, CommandHint("cargo build", "Build Rust crate/workspace", "medium", "Cargo.toml"))

    for java_project in analysis.java_projects:
        if java_project.build_tool == "maven" or _has_file(analysis, "pom.xml"):
            _append_command(hints, seen, CommandHint("mvn test", "Run Java tests", "medium", "pom.xml"))
            _append_command(hints, seen, CommandHint("mvn package", "Build Java package", "medium", "pom.xml"))
        if (
            java_project.build_tool == "gradle"
            or _has_file(analysis, "build.gradle")
            or _has_file(analysis, "build.gradle.kts")
        ):
            gradle = "gradlew.bat" if _has_file(analysis, "gradlew.bat") else "gradle"
            _append_command(hints, seen, CommandHint(f"{gradle} test", "Run Java tests", "medium", "Gradle build file"))
            _append_command(
                hints, seen, CommandHint(f"{gradle} build", "Build Java project", "medium", "Gradle build file")
            )

    if analysis.dotnet_solutions or analysis.dotnet_projects:
        _append_command(
            hints, seen, CommandHint("dotnet restore", "Restore .NET dependencies", "medium", "solution/project file")
        )
        _append_command(hints, seen, CommandHint("dotnet test", "Run .NET tests", "low", "solution/project file"))
        _append_command(
            hints, seen, CommandHint("dotnet build", "Build .NET solution/project", "medium", "solution/project file")
        )

    return hints


def _is_test_or_temp(rel_path: str) -> bool:
    """Check if a file is likely a test or temp/debug script."""
    lower = rel_path.lower()
    parts = Path(lower).parts
    if any(p.startswith("test") for p in parts):
        return True
    if any(p in ("tests", "testing", "debug") for p in parts):
        return True
    name = Path(lower).name
    if name.startswith("debug_") or name.startswith("temp_") or name.startswith("tmp_"):
        return True
    return False


def _make_anchor(text: str) -> str:
    """Convert a heading text to a markdown anchor."""
    return text.lower().strip().replace(" ", "-").replace("/", "").replace(".", "").replace("(", "").replace(")", "")


def _toc_for_headings(headings: list[str]) -> list[str]:
    """Generate a simple markdown TOC from heading texts."""
    lines = ["## Table of Contents", ""]
    for h in headings:
        lines.append(f"- [{h}](#{_make_anchor(h)})")
    lines.append("")
    return lines


def _is_compact_eligible(analysis: AnalysisResult) -> bool:
    """True when compact profile omits optional sections."""
    return analysis.profile == "compact"


def _maybe_errors_section(analysis: AnalysisResult) -> list[str]:
    if not analysis.errors:
        return []
    lines = [
        "## Errors",
        "",
        "The following non-fatal errors were encountered during analysis:",
        "",
    ]
    for err in analysis.errors[:30]:
        lines.append(f"- {err}")
    lines.append("")
    return lines


def _render_evidence_section(analysis: AnalysisResult, profile: str) -> list[str]:
    """Render an Evidence section from the analysis evidence set."""
    ev = analysis.evidence_set
    if not ev:
        return []
    lines: list[str] = ["## Evidence", ""]
    observed = ev.by_kind(EvidenceKind.OBSERVED)
    inferred = ev.by_kind(EvidenceKind.INFERRED)
    unknowns = ev.by_kind(EvidenceKind.UNKNOWN)
    unsupported = ev.by_kind(EvidenceKind.UNSUPPORTED)
    errors = ev.by_kind(EvidenceKind.ERROR)

    if observed:
        lines.append("### Observed")
        for e in observed[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    if inferred:
        lines.append("### Inferred")
        for e in inferred[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    if unknowns:
        lines.append("### Unknown")
        for e in unknowns[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    if unsupported:
        lines.append("### Unsupported")
        for e in unsupported[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    if errors:
        lines.append("### Errors")
        for e in errors[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    return lines


def render_project_overview(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    generated_at: str | None = None,
) -> RenderResult:
    """Generate PROJECT_OVERVIEW.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "PROJECT_OVERVIEW.md"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()

    headings = [
        "Project Metadata",
        "Root Files",
        "Source Layout",
        "Entry Points",
        "Dependencies",
    ]

    lines: list[str] = [
        GENERATED_HEADER,
    ]
    lines += _render_metadata_block(repo_path, analysis, timestamp)
    lines += [
        f"# Project Overview: {Path(repo_path).resolve().name}",
        "",
        f"- **Detected types**: {', '.join(detect.project_types)}",
        f"- **Evidence**: {', '.join(f'{k} ({v})' for k, v in detect.evidence.items())}",
        "",
    ]

    has_langs = any(
        [
            analysis.python_modules,
            analysis.node_packages,
            analysis.dotnet_projects,
            analysis.rust_crates,
            analysis.go_modules,
            analysis.java_projects,
        ]
    )
    compact_eligible = _is_compact_eligible(analysis)
    if has_langs and not (compact_eligible and len(analysis.project_types) <= 1):
        headings.insert(4, "Language Summaries")

    # Add evidence heading if there is evidence and profile is not compact on tiny repo
    if analysis.evidence_set and not compact_eligible:
        headings.insert(1, "Evidence")

    lines += _toc_for_headings(headings)

    # Metadata section
    meta = analysis.metadata
    lines += [
        "## Project Metadata",
        "",
    ]
    if meta.name:
        lines.append(f"- **Name**: {meta.name}")
    if meta.description:
        lines.append(f"- **Description**: {meta.description}")
    if meta.version:
        lines.append(f"- **Version**: {meta.version}")
    if meta.license:
        lines.append(f"- **License**: {meta.license}")
    if meta.authors:
        lines.append(f"- **Authors**: {', '.join(meta.authors)}")
    if meta.homepage:
        lines.append(f"- **Homepage**: {meta.homepage}")
    if meta.repository:
        lines.append(f"- **Repository**: {meta.repository}")
    if meta.keywords:
        lines.append(f"- **Keywords**: {', '.join(meta.keywords)}")
    if not any([meta.name, meta.description, meta.version, meta.license, meta.authors]):
        lines.append("_No project metadata found in config files._")
    lines.append("")

    if analysis.evidence_set and not compact_eligible:
        lines += _render_evidence_section(analysis, analysis.profile)

    lines += [
        "## Root Files",
        "",
        _join(analysis.root_files[: get_profile_limit(analysis.profile, "root_files")]),
        "",
        "## Source Layout",
        "",
    ]

    # Source directories for all stacks
    lines.append(_join(analysis.source_directories[: get_profile_limit(analysis.profile, "source_dirs")]))
    lines.append("")

    # Python module detail as subsection
    if analysis.python_modules:
        lines.append("### Python modules")
        lines.append("")
        source_modules = [m for m in analysis.python_modules if not _is_test_or_temp(m.rel_path)]
        pkg_tree: dict[str, list[str]] = {}
        for m in source_modules:
            parts = Path(m.rel_path).parts
            if len(parts) >= 2:
                pkg_name = parts[0]
                sub = "/".join(parts[1:])
            else:
                pkg_name = "root"
                sub = m.rel_path
            pkg_tree.setdefault(pkg_name, []).append(sub)

        limit = get_profile_limit(analysis.profile, "python_modules_display")
        # Rank package groups by importance
        ranked_pkgs = sorted(pkg_tree.items(), key=lambda item: score_path(item[0]), reverse=True)
        for pkg_name, files in ranked_pkgs:
            lines.append(f"- {_safe_inline_code(pkg_name + '/')} ({len(files)} files)")
            for f in sorted(files)[:limit]:
                lines.append(f"  - {_safe_inline_code(f)}")
            if len(files) > limit:
                lines.append(f"  - ... and {len(files) - limit} more")
            lines.append("")

    lines += [
        "## Entry Points",
        "",
        _join(analysis.likely_entry_points[: get_profile_limit(analysis.profile, "entry_points")]),
        "",
    ]

    # Dependencies section
    lines += [
        "## Dependencies",
        "",
    ]
    has_deps = False
    if analysis.python_dependencies:
        lines.append("### Python Runtime")
        for dep in analysis.python_dependencies[: get_profile_limit(analysis.profile, "deps")]:
            lines.append(f"- {dep}")
        lines.append("")
        has_deps = True
    if analysis.python_dev_dependencies:
        lines.append("### Python Development")
        for dep in analysis.python_dev_dependencies[: get_profile_limit(analysis.profile, "dev_deps")]:
            lines.append(f"- {dep}")
        lines.append("")
        has_deps = True

    # Node deps from product packages
    node_product_deps: list[str] = []
    node_dev_deps: list[str] = []
    for pkg in analysis.node_packages:
        if pkg.category == "product" and pkg.dependencies:
            node_product_deps.extend(pkg.dependencies)
        if pkg.dev_dependencies:
            node_dev_deps.extend(pkg.dev_dependencies)
    if node_product_deps:
        lines.append("### Node Runtime")
        for dep in sorted(set(node_product_deps))[: get_profile_limit(analysis.profile, "deps")]:
            lines.append(f"- {dep}")
        lines.append("")
        has_deps = True
    if node_dev_deps:
        lines.append("### Node Development")
        for dep in sorted(set(node_dev_deps))[: get_profile_limit(analysis.profile, "dev_deps")]:
            lines.append(f"- {dep}")
        lines.append("")
        has_deps = True

    if analysis.rust_crates and analysis.rust_crates[0].dependencies:
        lines.append("### Rust")
        for dep in analysis.rust_crates[0].dependencies[: get_profile_limit(analysis.profile, "deps")]:
            lines.append(f"- {dep}")
        lines.append("")
        has_deps = True
    go_deps = []
    for mod in analysis.go_modules:
        go_deps.extend(mod.dependencies)
    if go_deps:
        lines.append("### Go")
        for dep in sorted(set(go_deps))[: get_profile_limit(analysis.profile, "deps")]:
            lines.append(f"- {dep}")
        lines.append("")
        has_deps = True
    java_deps = []
    for java_proj in analysis.java_projects:
        java_deps.extend(java_proj.dependencies)
    if java_deps:
        lines.append("### Java")
        for dep in sorted(set(java_deps))[: get_profile_limit(analysis.profile, "deps")]:
            lines.append(f"- {dep}")
        lines.append("")
        has_deps = True

    if not has_deps:
        lines.append("_No dependencies identified._")
        lines.append("")

    lines += [
        "",
    ]

    if analysis.python_modules:
        lines += [
            "### Python Summary",
            "",
            f"Modules scanned: {len(analysis.python_modules)}",
            "",
        ]
        entry_mods = [m for m in analysis.python_modules if m.is_entry_point][
            : get_profile_limit(analysis.profile, "python_modules_display")
        ]
        if entry_mods:
            lines += ["#### Likely Python Entry Points", ""]
            for m in entry_mods:
                lines.append(f"- {_safe_inline_code(m.rel_path)}")
            lines.append("")
        classes: list[str] = []
        funcs: list[str] = []
        for m in analysis.python_modules:
            for c in m.classes:
                classes.append(f"{m.rel_path}::{c}")
            for f in m.functions:
                funcs.append(f"{m.rel_path}::{f}")
        lines += [f"Classes: {len(classes)}", f"Functions: {len(funcs)}", ""]

    if analysis.node_packages:
        product_pkgs = [p for p in analysis.node_packages if p.category == "product"]
        tooling_pkgs = [p for p in analysis.node_packages if p.category == "tooling"]
        other_pkgs = [p for p in analysis.node_packages if p.category not in ("product", "tooling")]
        display_pkgs = (product_pkgs + other_pkgs + tooling_pkgs)[
            : get_profile_limit(analysis.profile, "python_modules_display")
        ]
        for pkg in display_pkgs:
            cat_label = f" ({pkg.category})" if pkg.category else ""
            lines += [f"### Node/JS Summary{cat_label}", ""]
            if pkg.name:
                lines.append(f"Package: {_safe_inline_code(pkg.name)}")
            if pkg.rel_path and pkg.rel_path != "package.json":
                lines.append(f"Path: {_safe_inline_code(pkg.rel_path)}")
            if pkg.scripts:
                lines += ["#### Scripts", ""]
                for k, v in list(pkg.scripts.items())[: get_profile_limit(analysis.profile, "python_modules_display")]:
                    lines.append(f"- {_safe_inline_code(k)}: {_safe_inline_code(v)}")
                lines.append("")
            lines.append(f"JS/TS files: {len(pkg.files)}")
            if pkg.classes:
                lines.append(f"Classes: {len(pkg.classes)}")
            if pkg.functions:
                lines.append(f"Functions: {len(pkg.functions)}")
            if pkg.exports:
                lines.append(f"Exports: {len(pkg.exports)}")
            lines.append("")
        if len(analysis.node_packages) > len(display_pkgs):
            lines.append(f"_... and {len(analysis.node_packages) - len(display_pkgs)} more package(s)_")
            lines.append("")

    if analysis.dotnet_projects:
        lines += ["### .NET Summary", ""]
        for sol in analysis.dotnet_solutions:
            lines.append(f"- Solution: {_safe_inline_code(sol.name)} ({sol.rel_path})")
        for proj in analysis.dotnet_projects[: get_profile_limit(analysis.profile, "python_modules_display")]:
            lines.append(f"- Project: {_safe_inline_code(proj.name)} ({proj.rel_path})")
            if proj.target_frameworks:
                lines.append(f"  - Targets: {', '.join(proj.target_frameworks)}")
            if proj.output_type:
                lines.append(f"  - Output: {proj.output_type}")
            if proj.classes:
                lines.append(f"  - Classes: {len(proj.classes)}")
        lines.append("")

    if analysis.rust_crates:
        crate = analysis.rust_crates[0]
        lines += ["### Rust Summary", ""]
        if crate.name:
            lines.append(f"Crate: {_safe_inline_code(crate.name)}")
        lines.append(f"Modules: {len(crate.modules)}")
        if crate.traits:
            lines.append(f"Traits: {len(crate.traits)}")
        if crate.impls:
            lines.append(f"Impls: {len(crate.impls)}")
        if crate.entry_points:
            lines += ["#### Entry Points", ""]
            for ep in crate.entry_points:
                lines.append(f"- {_safe_inline_code(ep)}")
            lines.append("")
        if crate.dependencies:
            lines += ["#### Dependencies", ""]
            for dep in crate.dependencies[: get_profile_limit(analysis.profile, "deps")]:
                lines.append(f"- {dep}")
            lines.append("")

    if analysis.go_modules:
        lines += ["### Go Summary", ""]
        for mod in analysis.go_modules:
            label = f" {_safe_inline_code(mod.rel_path)}" if mod.rel_path and mod.rel_path != "." else ""
            lines.append(f"**Module{label}**")
            if mod.name:
                lines.append(f"- Name: {_safe_inline_code(mod.name)}")
            lines.append(f"- Packages: {len(mod.packages)}")
            if mod.structs:
                lines.append(f"- Structs: {len(mod.structs)}")
            if mod.interfaces:
                lines.append(f"- Interfaces: {len(mod.interfaces)}")
            if mod.entry_points:
                lines += ["  - Entry Points", ""]
                for ep in mod.entry_points:
                    lines.append(f"    - {_safe_inline_code(ep)}")
                lines.append("")
            if mod.dependencies:
                lines += ["  - Dependencies", ""]
                for dep in mod.dependencies[: get_profile_limit(analysis.profile, "deps")]:
                    lines.append(f"    - {dep}")
                lines.append("")
            lines.append("")

    if analysis.java_projects:
        lines += ["### Java Summary", ""]
        for java_proj in analysis.java_projects:
            label = (
                f" {_safe_inline_code(java_proj.rel_path)}" if java_proj.rel_path and java_proj.rel_path != "." else ""
            )
            lines.append(f"**Project{label}**")
            if java_proj.name:
                lines.append(f"- Name: {_safe_inline_code(java_proj.name)}")
            if java_proj.build_tool:
                lines.append(f"- Build tool: {_safe_inline_code(java_proj.build_tool)}")
            lines.append(f"- Classes: {len(java_proj.classes)}")
            if java_proj.methods:
                lines.append(f"- Methods: {len(java_proj.methods)}")
            if java_proj.annotations:
                lines.append(f"- Annotations: {len(java_proj.annotations)}")
            if java_proj.entry_points:
                lines += ["  - Entry Points", ""]
                for ep in java_proj.entry_points:
                    lines.append(f"    - {_safe_inline_code(ep)}")
                lines.append("")
            if java_proj.dependencies:
                lines += ["  - Dependencies", ""]
                for dep in java_proj.dependencies[: get_profile_limit(analysis.profile, "deps")]:
                    lines.append(f"    - {dep}")
                lines.append("")
            lines.append("")

    lines += _maybe_errors_section(analysis)
    if not compact_eligible:
        lines += [
            "## Generic Notes",
            "",
            f"- Test directories: {', '.join(analysis.test_directories[:10]) or 'None identified'}",
            f"- Docs files: {len(analysis.docs_files)}",
            f"- Config files: {len(analysis.config_files)}",
            "",
        ]
    lines += [
        "---",
        "*This file was generated by context-crafter-mcp and may be regenerated.*",
        "",
    ]

    write_redacted_text(path, "\n".join(lines))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.scan_summary.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=analysis.scan_summary,
    )


def render_repo_map(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    generated_at: str | None = None,
) -> RenderResult:
    """Generate REPO_MAP.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "REPO_MAP.md"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()

    lines: list[str] = [
        GENERATED_HEADER,
    ]
    lines += _render_metadata_block(repo_path, analysis, timestamp)
    lines += [
        f"# Repository Map: {Path(repo_path).resolve().name}",
        "",
        "## Directory Tree",
        "",
        "```",
    ]
    lines += analysis.directory_tree[: get_profile_limit(analysis.profile, "tree_max_lines")]
    lines += [
        "```",
        "",
        "## Important Config Files",
        "",
        _join(analysis.config_files[: get_profile_limit(analysis.profile, "config_files")]),
        "",
        "## Likely Entry Points",
        "",
        _join(analysis.likely_entry_points[: get_profile_limit(analysis.profile, "entry_points")]),
        "",
        "## Test Directories",
        "",
        _join(analysis.test_directories[: get_profile_limit(analysis.profile, "test_dirs")]),
        "",
        "## Docs Directories",
        "",
        _join(analysis.docs_files[: get_profile_limit(analysis.profile, "docs_files")]),
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    write_redacted_text(path, "\n".join(lines))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.scan_summary.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=analysis.scan_summary,
    )


def _extract_architecture_notes(analysis: AnalysisResult) -> dict[str, list[str]]:
    """Extract architecture patterns and notes from the analysis."""
    notes: dict[str, list[str]] = {
        "patterns": [],
        "abstractions": [],
        "module_relationships": [],
        "concerns": [],
    }

    # Python-specific architecture analysis
    if analysis.python_modules:
        source_modules = [m for m in analysis.python_modules if not _is_test_or_temp(m.rel_path)]

        # Detect plugin/registry pattern
        registry_modules = [
            m for m in source_modules if "registry" in m.rel_path.lower() or "register" in " ".join(m.functions)
        ]
        if registry_modules:
            notes["patterns"].append("Plugin/Registry pattern detected (dynamic analyzer registration).")

        # Detect pipeline/orchestration pattern
        pipeline_modules = [
            m
            for m in source_modules
            if any(p in m.rel_path.lower() for p in ["graph", "pipeline", "workflow", "orchestr"])
        ]
        if pipeline_modules:
            notes["patterns"].append("Pipeline/Orchestration pattern detected (state-machine or graph-based flow).")

        # Detect server/API pattern
        server_modules = [m for m in source_modules if "server" in m.rel_path.lower()]
        if server_modules:
            notes["patterns"].append("Server/API pattern detected.")

        # Count key abstractions
        all_classes: list[str] = []
        all_async_funcs: list[str] = []
        for m in source_modules:
            for c in m.classes:
                all_classes.append(f"{m.rel_path}::{c}")
            for f in m.async_functions:
                all_async_funcs.append(f"{m.rel_path}::{f}")

        if all_classes:
            notes["abstractions"].append(f"{len(all_classes)} class(es) defined across source modules.")
            for c in all_classes[: get_profile_limit(analysis.profile, "abstractions")]:
                notes["abstractions"].append(f"  - {_safe_inline_code(c)}")
            if len(all_classes) > 10:
                notes["abstractions"].append(f"  - ... and {len(all_classes) - 10} more")

        if all_async_funcs:
            notes["abstractions"].append(
                f"{len(all_async_funcs)} async function(s) — likely I/O-bound or event-driven architecture."
            )

        # Module relationships
        internal_edges: set[tuple[str, str]] = set()
        for m in source_modules:
            raw_src = m.module_name or Path(m.rel_path).parts[0] if Path(m.rel_path).parts else ""
            # Strip src/ prefixes
            for prefix in ("src.", "lib.", "source.", "sources."):
                if raw_src.startswith(prefix):
                    raw_src = raw_src[len(prefix) :]
            src_pkg = raw_src.split(".")[0] if raw_src else ""
            for imp in m.internal_imports:
                first = imp.split(".")[0]
                if first and first != src_pkg:
                    internal_edges.add((src_pkg, first))

        if internal_edges:
            notes["module_relationships"].append("Cross-module dependencies detected:")
            for src, tgt in sorted(internal_edges)[: get_profile_limit(analysis.profile, "internal_edges")]:
                notes["module_relationships"].append(f"  - {_safe_inline_code(src)} → {_safe_inline_code(tgt)}")
            if len(internal_edges) > get_profile_limit(analysis.profile, "internal_edges"):
                notes["module_relationships"].append(f"  - ... and {len(internal_edges) - 15} more")

        # Cyclic dependency check (simple)
        cycles: list[str] = []
        for src, tgt in internal_edges:
            if (tgt, src) in internal_edges:
                cycle = f"{_safe_inline_code(src)} ↔ {_safe_inline_code(tgt)}"
                if cycle not in cycles:
                    cycles.append(cycle)
        if cycles:
            notes["concerns"].append("Potential bidirectional/cyclic dependencies detected:")
            for c in cycles[: get_profile_limit(analysis.profile, "cycles")]:
                notes["concerns"].append(f"  - {c}")

        # Large modules
        large_modules = [m for m in source_modules if len(m.classes) > 10 or len(m.functions) > 20]
        if large_modules:
            notes["concerns"].append("Large modules (high class/function count) — consider decomposition:")
            for m in large_modules[: get_profile_limit(analysis.profile, "large_modules")]:
                notes["concerns"].append(
                    f"  - {_safe_inline_code(m.rel_path)} ({len(m.classes)} classes, {len(m.functions)} functions)"
                )

    # Go-specific patterns
    if analysis.go_modules:
        all_interfaces = []
        all_entry_points = []
        for mod in analysis.go_modules:
            all_interfaces.extend(mod.interfaces)
            all_entry_points.extend(mod.entry_points)
        if len(all_interfaces) > 3:
            notes["patterns"].append("Interface-heavy design (Go idiomatic polymorphism).")
        if all_entry_points:
            notes["patterns"].append("CLI/service architecture detected (main package entry points).")

    # Java-specific patterns
    if analysis.java_projects:
        all_annotations = []
        total_classes = 0
        for java_proj in analysis.java_projects:
            all_annotations.extend(java_proj.annotations)
            total_classes += len(java_proj.classes)
        spring_annotations = {"Component", "Service", "Controller", "Repository", "Entity", "SpringBootApplication"}
        found_spring = spring_annotations & set(all_annotations)
        if found_spring:
            notes["patterns"].append(f"Spring framework detected ({', '.join(sorted(found_spring))}).")
        if total_classes > 20:
            notes["abstractions"].append(f"{total_classes} class(es) — class-heavy architecture.")

    # Node-specific patterns (check product packages first)
    if analysis.node_packages:
        web_frameworks = {"express", "fastify", "koa", "hapi", "nest"}
        frontend_frameworks = {"react", "vue", "angular", "svelte", "next"}
        for node_pkg in analysis.node_packages:
            if node_pkg.category == "vendor":
                continue
            all_deps = set(node_pkg.dependencies) | set(node_pkg.dev_dependencies)
            found_web = web_frameworks & all_deps
            found_fe = frontend_frameworks & all_deps
            if found_web:
                notes["patterns"].append(f"Web server framework detected ({', '.join(sorted(found_web))}).")
            if found_fe:
                notes["patterns"].append(f"Frontend framework detected ({', '.join(sorted(found_fe))}).")

    # Rust-specific patterns
    if analysis.rust_crates:
        crate = analysis.rust_crates[0]
        if crate.traits and len(crate.traits) > 2:
            notes["patterns"].append("Trait-based polymorphism detected.")
        if any("tokio" in d for d in crate.dependencies):
            notes["patterns"].append("Async runtime detected (tokio).")

    return notes


def render_architecture_summary(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    generated_at: str | None = None,
) -> RenderResult:
    """Generate ARCHITECTURE_SUMMARY.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "ARCHITECTURE_SUMMARY.md"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()

    arch_notes = _extract_architecture_notes(analysis)
    has_patterns = any(arch_notes.values())
    compact_eligible = _is_compact_eligible(analysis)

    headings: list[str] = [
        "Detected Stacks",
        "Major Source Directories",
        "Likely Runtime Entry Points",
        "Testing Layout",
        "Packaging / Build System",
        "Documentation State",
    ]
    if arch_notes["patterns"] or not compact_eligible:
        headings.append("Architecture Patterns")
    if arch_notes["abstractions"] or not compact_eligible:
        headings.append("Key Abstractions")
    if arch_notes["module_relationships"] or not compact_eligible:
        headings.append("Module Relationships")
    if analysis.workspace_packages or len(analysis.node_packages) > 1:
        headings.insert(3, "Workspace / Monorepo Layout")
    headings.append("Risks / Unknowns")

    if analysis.errors:
        headings.insert(0, "Errors")

    lines: list[str] = [
        GENERATED_HEADER,
    ]
    lines += _render_metadata_block(repo_path, analysis, timestamp)
    lines += [
        f"# Architecture Summary: {Path(repo_path).resolve().name}",
        "",
    ]

    lines += _toc_for_headings(headings)
    lines += _maybe_errors_section(analysis)

    lines += [
        "## Detected Stacks",
        "",
        _join(detect.project_types),
        "",
        "## Major Source Directories",
        "",
    ]
    for d in analysis.source_directories[: get_profile_limit(analysis.profile, "source_dirs")]:
        cat = classify_path(d)
        tag = f" [{cat.value}]" if cat != PathCategory.UNKNOWN else ""
        lines.append(f"- {_safe_inline_code(d)}{tag}")
    lines += ["", "## Likely Runtime Entry Points", ""]
    for ep in analysis.likely_entry_points[: get_profile_limit(analysis.profile, "entry_points")]:
        cat = classify_path(ep)
        tag = f" [{cat.value}]" if cat not in (PathCategory.UNKNOWN, PathCategory.PRODUCT) else ""
        lines.append(f"- {_safe_inline_code(ep)}{tag}")
    lines += [
        "",
        "## Testing Layout",
        "",
        _join(analysis.test_directories[: get_profile_limit(analysis.profile, "test_dirs")]),
        "",
        "## Packaging / Build System",
        "",
    ]

    if "python" in detect.project_types:
        lines.append("- Python project detected (look for `pyproject.toml`, `setup.py`)")
    if "node" in detect.project_types:
        lines.append("- Node project detected (look for `package.json`, build scripts)")
    if "dotnet" in detect.project_types:
        lines.append("- .NET project detected (look for `.sln`, `.csproj`)")
    if "rust" in detect.project_types:
        lines.append("- Rust project detected (look for `Cargo.toml`)")
    if "go" in detect.project_types:
        lines.append("- Go project detected (look for `go.mod`)")
    if "java" in detect.project_types:
        java_markers = detect.markers.get("java", [])
        has_pom = any("pom.xml" in m for m in java_markers)
        has_gradle = any("build.gradle" in m for m in java_markers)
        if has_pom and has_gradle:
            lines.append("- Java project detected (look for `pom.xml`, `build.gradle`)")
        elif has_pom:
            lines.append("- Java project detected (look for `pom.xml`)")
        elif has_gradle:
            lines.append("- Java project detected (look for `build.gradle`)")
        else:
            lines.append("- Java project detected")
    lines.append("")

    if analysis.workspace_packages or len(analysis.node_packages) > 1:
        lines += [
            "## Workspace / Monorepo Layout",
            "",
        ]
        if analysis.workspace_packages:
            lines.append(f"- Workspace patterns: {', '.join(analysis.workspace_packages)}")
        for pkg in analysis.node_packages[:5]:
            pkg_cat = pkg.category or "unknown"
            lines.append(
                f"- {_safe_inline_code(pkg.name or pkg.rel_path or 'unknown')} [{pkg_cat}]: {len(pkg.files)} file(s), {len(pkg.dependencies)} runtime dep(s)"
            )
        if len(analysis.node_packages) > 5:
            lines.append(f"- ... and {len(analysis.node_packages) - 5} more package(s)")
        lines.append("")

    lines += [
        "## Documentation State",
        "",
        f"- README: {'Yes' if any('readme' in f.lower() for f in analysis.root_files) else 'Not obvious'}",
        f"- Docs files: {len(analysis.docs_files)}",
        "",
    ]

    if arch_notes["patterns"] or not compact_eligible:
        lines += [
            "## Architecture Patterns",
            "",
        ]
        if arch_notes["patterns"]:
            for note in arch_notes["patterns"]:
                lines.append(f"- {note}")
        else:
            lines.append("_No specific architectural patterns identified._")
        lines.append("")

    if arch_notes["abstractions"] or not compact_eligible:
        lines += [
            "## Key Abstractions",
            "",
        ]
        if arch_notes["abstractions"]:
            for note in arch_notes["abstractions"]:
                lines.append(f"- {note}")
        else:
            lines.append("_No significant abstractions identified._")
        lines.append("")

    if arch_notes["module_relationships"] or not compact_eligible:
        lines += [
            "## Module Relationships",
            "",
        ]
        if arch_notes["module_relationships"]:
            for note in arch_notes["module_relationships"]:
                lines.append(note)
        else:
            lines.append("_No cross-module relationships identified._")
        lines.append("")

    lines += [
        "## Risks / Unknowns",
        "",
    ]

    if arch_notes["concerns"]:
        for note in arch_notes["concerns"]:
            lines.append(f"- {note}")

    if not analysis.likely_entry_points:
        lines.append("- No clear entry points were identified automatically.")
    if not analysis.test_directories:
        lines.append("- No test directories were identified automatically.")
    if not analysis.config_files:
        lines.append("- No obvious config files found.")
    if len(analysis.root_files) < 3:
        lines.append("- Repository root appears sparse; may be a monorepo subdirectory or incomplete checkout.")
    ss = analysis.scan_summary
    total_skipped = sum(ss.skipped_reasons.values())
    if ss.budget_exhausted or total_skipped > 100:
        lines.append(
            f"- Scanner budget exhausted or heavily constrained: {total_skipped} file(s) skipped. "
            "Conclusions are based on a bounded sample."
        )
    if ss.category_counts:
        product_count = ss.category_counts.get("product", 0)
        unknown_count = ss.category_counts.get("unknown", 0)
        vendor_count = (
            ss.category_counts.get("vendor", 0)
            + ss.category_counts.get("generated", 0)
            + ss.category_counts.get("fixture", 0)
        )
        total_scanned = ss.files_scanned
        if total_scanned > 0 and (product_count + unknown_count) < total_scanned * 0.2:
            lines.append(
                f"- Scan composition is mostly vendor/generated/tooling ({vendor_count} of {total_scanned} files). "
                "Primary product surface may be smaller than file count suggests."
            )
    if analysis.errors:
        lines.append("- Some files could not be parsed; see analysis errors.")
    if not has_patterns and not any(
        [
            "python" in detect.project_types,
            "node" in detect.project_types,
            "dotnet" in detect.project_types,
            "rust" in detect.project_types,
            "go" in detect.project_types,
            "java" in detect.project_types,
        ]
    ):
        lines.append("- No mainstream stack markers found; architecture inference is limited.")
    if not arch_notes["concerns"] and analysis.likely_entry_points and analysis.test_directories:
        lines.append("- No obvious architectural concerns detected from static analysis.")

    lines += [
        "",
        "---",
        "*This analysis is based purely on static inspection. It may miss runtime architecture or cloud infra.*",
        "",
    ]

    write_redacted_text(path, "\n".join(lines))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.scan_summary.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=analysis.scan_summary,
    )


def render_ai_context_index(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    generated_at: str | None = None,
) -> RenderResult:
    """Generate AI_CONTEXT_INDEX.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "AI_CONTEXT_INDEX.md"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()

    lines: list[str] = [
        GENERATED_HEADER,
    ]
    lines += _render_metadata_block(repo_path, analysis, timestamp)
    lines += [
        f"# AI Context Index: {Path(repo_path).resolve().name}",
        "",
        f"- **Detected types**: {', '.join(detect.project_types)}",
        "",
        "## Generated Files",
        "",
        "| File | Purpose |",
        "|------|---------|",
        "| `AI_CONTEXT_INDEX.md` | This index |",
        "| `PROJECT_OVERVIEW.md` | Project metadata, stacks, entry points |",
        "| `REPO_MAP.md` | Directory tree and key files |",
        "| `DEPENDENCY_GRAPH.md` | Mermaid dependency graph |",
        "| `ARCHITECTURE_SUMMARY.md` | Architecture patterns and risks |",
        "| `AGENT_BRIEF.md` | Concise agent-ready summary |",
        "| `COMMANDS.md` | Statically inferred setup, test, and build commands |",
        "| `VALIDATION_REPORT.md` | Output validation status |",
        "| `SCAN_REPORT.md` | Scan coverage and skipped items |",
        "",
        "## Quick Navigation",
        "",
        "- [Project Overview](PROJECT_OVERVIEW.md)",
        "- [Repository Map](REPO_MAP.md)",
        "- [Dependency Graph](DEPENDENCY_GRAPH.md)",
        "- [Architecture Summary](ARCHITECTURE_SUMMARY.md)",
        "- [Agent Brief](AGENT_BRIEF.md)",
        "- [Commands](COMMANDS.md)",
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    write_redacted_text(path, "\n".join(lines))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.scan_summary.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=analysis.scan_summary,
    )


def render_commands(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    generated_at: str | None = None,
) -> RenderResult:
    """Generate COMMANDS.md with static, non-executed command hints."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "COMMANDS.md"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()
    hints = _collect_command_hints(analysis)

    lines: list[str] = [
        GENERATED_HEADER,
    ]
    lines += _render_metadata_block(repo_path, analysis, timestamp)
    lines += [
        f"# Commands: {Path(repo_path).resolve().name}",
        "",
        f"- **Detected types**: {', '.join(detect.project_types)}",
        "- **Execution status**: not executed; commands are inferred from static repository files.",
        "- **Confidence**: high means the command comes from an explicit script; medium/low means it is inferred from markers and should be verified locally.",
        "",
        "## Command Hints",
        "",
    ]
    if hints:
        lines += [
            "| Purpose | Command | Confidence | Evidence |",
            "|---------|---------|------------|----------|",
        ]
        for hint in hints:
            lines.append(
                f"| {hint.purpose} | {_safe_inline_code(hint.command)} | {hint.confidence} | {hint.evidence} |"
            )
        lines.append("")
    else:
        lines += [
            "_No setup, test, build, or lint commands could be inferred from supported project markers._",
            "",
        ]

    lines += [
        "## Safety Notes",
        "",
        "- Static analysis only; no command in this file was executed during generation.",
        "- Treat inferred commands as a starting point, especially in repositories with custom tooling.",
        "- Review commands before running them in shells, CI, or production environments.",
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    write_redacted_text(path, "\n".join(lines))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.scan_summary.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=analysis.scan_summary,
    )


def render_agent_brief(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    generated_at: str | None = None,
) -> RenderResult:
    """Generate AGENT_BRIEF.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "AGENT_BRIEF.md"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()

    compact_eligible = _is_compact_eligible(analysis)

    # Ranked entry points with category tags
    ep_lines: list[str] = []
    for ep in analysis.likely_entry_points[: get_profile_limit(analysis.profile, "entry_points")]:
        cat = classify_path(ep)
        tag = f" [{cat.value}]" if cat not in (PathCategory.UNKNOWN, PathCategory.PRODUCT) else ""
        ep_lines.append(f"- {_safe_inline_code(ep)}{tag}")
    if not ep_lines:
        ep_lines = ["_None found_"]

    src_lines: list[str] = []
    for d in analysis.source_directories[: get_profile_limit(analysis.profile, "source_dirs")]:
        cat = classify_path(d)
        tag = f" [{cat.value}]" if cat != PathCategory.UNKNOWN else ""
        src_lines.append(f"- {_safe_inline_code(d)}{tag}")
    if not src_lines:
        src_lines = ["_None found_"]

    lines: list[str] = [
        GENERATED_HEADER,
    ]
    lines += _render_metadata_block(repo_path, analysis, timestamp)
    lines += [
        f"# Agent Brief: {Path(repo_path).resolve().name}",
        "",
        f"- **Types**: {', '.join(detect.project_types)}",
        "",
        "## What this is",
        "",
        "Compact, source-grounded context for AI coding agents.",
        "",
        "## Entry points",
        "",
    ]
    lines.extend(ep_lines)
    lines.append("")

    if analysis.source_directories or not compact_eligible:
        lines += [
            "## Source layout",
            "",
        ]
        lines.extend(src_lines)
        lines += [
            "",
        ]

    if analysis.test_directories or not compact_eligible:
        lines += [
            "## Test layout",
            "",
            _join(analysis.test_directories[: get_profile_limit(analysis.profile, "test_dirs")]),
            "",
        ]

    lines += [
        "## Key dependencies",
        "",
    ]
    deps: list[str] = []
    if analysis.python_dependencies:
        deps.extend(analysis.python_dependencies[: get_profile_limit(analysis.profile, "deps")])
    node_product_deps = []
    for pkg in analysis.node_packages:
        if pkg.category == "product" and pkg.dependencies:
            node_product_deps.extend(pkg.dependencies)
    if node_product_deps:
        deps.extend(sorted(set(node_product_deps))[: get_profile_limit(analysis.profile, "deps")])
    if not deps and analysis.rust_crates and analysis.rust_crates[0].dependencies:
        deps.extend(analysis.rust_crates[0].dependencies[: get_profile_limit(analysis.profile, "deps")])
    if not deps and analysis.go_modules:
        go_deps = []
        for mod in analysis.go_modules:
            go_deps.extend(mod.dependencies)
        if go_deps:
            deps.extend(sorted(set(go_deps))[: get_profile_limit(analysis.profile, "deps")])
    if not deps and analysis.java_projects:
        java_deps = []
        for java_proj in analysis.java_projects:
            java_deps.extend(java_proj.dependencies)
        if java_deps:
            deps.extend(sorted(set(java_deps))[: get_profile_limit(analysis.profile, "deps")])
    lines.append(_join(deps))
    lines.append("")
    lines += [
        "## Warnings",
        "",
    ]
    ss = analysis.scan_summary
    total_skipped = sum(ss.skipped_reasons.values())
    if analysis.errors:
        lines.append(f"- {len(analysis.errors)} analysis error(s); see full reports.")
    if ss.budget_exhausted or total_skipped > 100:
        lines.append(
            f"- Scan budget pressure: {total_skipped} file(s) skipped. "
            "Output is based on a bounded sample, not an exhaustive scan."
        )
    vendor_heavy = False
    if ss.category_counts:
        product_count = ss.category_counts.get("product", 0)
        unknown_count = ss.category_counts.get("unknown", 0)
        vendor_count = (
            ss.category_counts.get("vendor", 0)
            + ss.category_counts.get("generated", 0)
            + ss.category_counts.get("fixture", 0)
        )
        total_scanned = ss.files_scanned
        if total_scanned > 0 and (product_count + unknown_count) < total_scanned * 0.2:
            vendor_heavy = True
            lines.append(
                f"- Vendor/generated files dominate scan ({vendor_count} of {total_scanned}). "
                "Primary product surface may be smaller than it appears."
            )
    if not analysis.errors and not (ss.budget_exhausted or total_skipped > 100) and not vendor_heavy:
        lines.append("- None.")
    lines.append("")

    # Evidence/unknowns for agent brief
    unknowns = analysis.evidence_set.by_kind(EvidenceKind.UNKNOWN)
    unsupported = analysis.evidence_set.by_kind(EvidenceKind.UNSUPPORTED)
    if unknowns or unsupported:
        lines += [
            "## Unknowns / Limitations",
            "",
        ]
        for e in unknowns[:5]:
            lines.append(f"- {e.message}")
        for e in unsupported[:5]:
            lines.append(f"- {e.message}")
        lines.append("")

    lines += [
        "---",
        "*Generated by context-crafter-mcp. Use PROJECT_OVERVIEW.md and ARCHITECTURE_SUMMARY.md for deeper detail.*",
        "",
    ]

    write_redacted_text(path, "\n".join(lines))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.scan_summary.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=analysis.scan_summary,
    )


def render_validation_report(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    written_files: list[str] | None = None,
    generated_at: str | None = None,
) -> RenderResult:
    """Generate VALIDATION_REPORT.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "VALIDATION_REPORT.md"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()

    # Validate the other required Markdown outputs (VALIDATION_REPORT.md is implicitly present)
    required = [
        "AI_CONTEXT_INDEX.md",
        "PROJECT_OVERVIEW.md",
        "REPO_MAP.md",
        "DEPENDENCY_GRAPH.md",
        "ARCHITECTURE_SUMMARY.md",
        "AGENT_BRIEF.md",
        "COMMANDS.md",
        "SCAN_REPORT.md",
    ]
    found: list[str] = []
    missing: list[str] = []
    written_set = {Path(w).name for w in (written_files or [])}
    for name in required:
        if name in written_set or (out / name).exists():
            found.append(name)
        else:
            missing.append(name)

    lines: list[str] = [
        GENERATED_HEADER,
    ]
    lines += _render_metadata_block(repo_path, analysis, timestamp)
    lines += [
        f"# Validation Report: {Path(repo_path).resolve().name}",
        "",
        "## Output Files",
        "",
        f"- Found: {len(found)}/{len(required)}",
        "",
        "### Found",
        "",
        _join(found),
        "",
    ]
    if missing:
        lines += [
            "### Missing",
            "",
            _join(missing),
            "",
        ]
    else:
        lines += [
            "### Missing",
            "",
            "_None._",
            "",
        ]

    lines += [
        "## Analysis Health",
        "",
        f"- Files scanned: {analysis.scan_summary.files_scanned}",
        f"- Errors: {len(analysis.errors)}",
        f"- Project types: {', '.join(detect.project_types)}",
        "",
    ]
    if analysis.errors:
        lines += [
            "### Errors",
            "",
        ]
        for err in analysis.errors[:20]:
            lines.append(f"- {err}")
        lines.append("")

    lines += [
        "## Result",
        "",
        "PASS" if not missing else "PARTIAL",
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    write_redacted_text(path, "\n".join(lines))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.scan_summary.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=analysis.scan_summary,
    )


def render_scan_report(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    generated_at: str | None = None,
) -> RenderResult:
    """Generate SCAN_REPORT.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "SCAN_REPORT.md"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()

    lines: list[str] = [
        GENERATED_HEADER,
    ]
    lines += _render_metadata_block(repo_path, analysis, timestamp)
    lines += [
        f"# Scan Report: {Path(repo_path).resolve().name}",
        "",
        "## Coverage",
        "",
        f"- Files scanned: {analysis.scan_summary.files_scanned}",
        f"- Root files: {len(analysis.root_files)}",
        f"- Source directories: {len(analysis.source_directories)}",
        f"- Test directories: {len(analysis.test_directories)}",
        f"- Config files: {len(analysis.config_files)}",
        f"- Docs files: {len(analysis.docs_files)}",
        "",
        "## Detected stacks",
        "",
        _join(detect.project_types),
        "",
    ]

    # Honest bounded-scan summary
    ss = analysis.scan_summary
    lines += [
        "## Scan bounds",
        "",
    ]
    if ss.budget_exhausted:
        lines.append(
            "- **Scanner budget exhausted.** Some files were skipped due to `max_files` or `max_files_per_dir` caps. "
            "Output is based on a bounded sample, not an exhaustive scan."
        )
    if ss.skipped_reasons:
        for reason, count in sorted(ss.skipped_reasons.items(), key=lambda x: -x[1]):
            lines.append(f"- Skipped (`{reason}`): {count}")
    if not ss.budget_exhausted and not ss.skipped_reasons:
        lines.append("_All reachable files within depth and size limits were scanned._")

    # Scan composition honesty
    if ss.category_counts:
        lines += ["", "### Scan composition", ""]
        for cat, count in sorted(ss.category_counts.items(), key=lambda x: -x[1]):
            lines.append(f"- {cat}: {count}")
        product_count = ss.category_counts.get("product", 0)
        unknown_count = ss.category_counts.get("unknown", 0)
        total_scanned = ss.files_scanned
        if total_scanned > 0 and (product_count + unknown_count) < total_scanned * 0.2:
            lines.append(
                "- **Warning:** Most scanned files are vendor, generated, or tooling. "
                "Primary product surface may be under-represented."
            )
        lines.append("")
    else:
        lines.append("")

    lines += [
        "## Skipped / Ignored",
        "",
        "- Symlinks: not followed",
        "- Hidden files: excluded by default",
        "- Ignored directories: .git, node_modules, venv, __pycache__, dist, build, target, bin, obj, .next, .turbo, .cache, .mypy_cache, .pytest_cache, .ruff_cache, vendor, vendors, third_party, generated, gen, autogen",
        "",
    ]
    if analysis.errors:
        lines += [
            "## Scan errors",
            "",
        ]
        for err in analysis.errors[:30]:
            lines.append(f"- {err}")
        lines.append("")
    else:
        lines += [
            "## Scan errors",
            "",
            "_None._",
            "",
        ]

    secret_evidence = analysis.evidence_set.by_analyzer("generic")
    secret_warnings = [e for e in secret_evidence if "secret" in e.message.lower()]
    lines += [
        "## Safety notes",
        "",
        "- Static analysis only; no code executed.",
        "- No network calls made during generation.",
        "- Output confined to repository root.",
    ]
    if secret_warnings:
        lines.append("- Potential secret files detected; review generated output before sharing:")
        for sw in secret_warnings[:5]:
            lines.append(f"  - `{sw.source_path}`")
    else:
        lines.append("- No obvious secret files detected (heuristic only).")
    lines += [
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    write_redacted_text(path, "\n".join(lines))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.scan_summary.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=analysis.scan_summary,
    )


def render_run_state(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    written_files: list[str],
    errors: list[str],
    generated_at: str | None = None,
) -> RenderResult:
    """Render a machine-readable JSON run-state file."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "RUN_STATE.json"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()

    ss = analysis.scan_summary
    total_skipped = sum(ss.skipped_reasons.values())
    warnings = analysis.evidence_set.warnings()
    state = {
        "version": __version__,
        "schema_mode": "additive",
        "timestamp": timestamp,
        "repo_path": repo_path,
        "project_types": detect.project_types,
        "profile": analysis.profile,
        "scan_config": {
            "max_depth": ss.max_depth,
            "max_files_per_dir": ss.max_files,
            "max_file_bytes": ss.max_file_bytes,
        },
        "files_scanned": ss.files_scanned,
        "scan_summary": {
            "files_scanned": ss.files_scanned,
            "dirs_scanned": ss.dirs_scanned,
            "files_skipped": ss.files_skipped,
            "dirs_skipped": ss.dirs_skipped,
            "budget_exhausted": ss.budget_exhausted,
            "skipped_reasons": ss.skipped_reasons,
            "category_counts": ss.category_counts,
        },
        "analyzer_summary": {
            "analyzers_run": detect.project_types,
            "files_parsed": analysis.analyzer_files_parsed,
        },
        "validation_summary": {
            "output_files_count": len(written_files) + 1,
            "errors_count": len(errors),
            "warnings_count": len(warnings),
            "bounded_scan": ss.budget_exhausted or total_skipped > 0,
        },
        "warnings": [e.message for e in warnings],
        "evidence_counts": {
            "observed": len(analysis.evidence_set.by_kind(EvidenceKind.OBSERVED)),
            "inferred": len(analysis.evidence_set.by_kind(EvidenceKind.INFERRED)),
            "unknown": len(analysis.evidence_set.by_kind(EvidenceKind.UNKNOWN)),
            "unsupported": len(analysis.evidence_set.by_kind(EvidenceKind.UNSUPPORTED)),
            "error": len(analysis.evidence_set.by_kind(EvidenceKind.ERROR)),
        },
        "analyzers_run": detect.project_types,
        "output_files": [str(Path(w).name) for w in written_files] + ["RUN_STATE.json"],
        "errors": errors,
    }

    import json

    write_redacted_text(path, json.dumps(state, indent=2))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=ss.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=ss,
    )


_MANIFEST_FILE_PURPOSES: dict[str, tuple[str, list[str], str]] = {
    "AI_CONTEXT_INDEX.md": ("index", ["human", "agent"], "Master navigation for the generated context bundle."),
    "PROJECT_OVERVIEW.md": (
        "overview",
        ["human", "agent"],
        "Project metadata, detected stacks, evidence, and dependencies.",
    ),
    "REPO_MAP.md": ("map", ["human", "agent"], "Repository tree and important source/config/test locations."),
    "DEPENDENCY_GRAPH.mmd": ("graph-source", ["automation"], "Raw Mermaid dependency graph source."),
    "DEPENDENCY_GRAPH.md": ("graph", ["human", "agent"], "Rendered dependency graph and dependency summary."),
    "ARCHITECTURE_SUMMARY.md": ("architecture", ["human", "agent"], "Architecture patterns, risks, and unknowns."),
    "AGENT_BRIEF.md": ("agent-brief", ["agent"], "Concise starting point for AI coding agents."),
    "COMMANDS.md": ("commands", ["human", "agent"], "Static command runbook with evidence and confidence."),
    "SCAN_REPORT.md": ("scan-report", ["human", "agent"], "Scan coverage, skipped items, bounds, and safety notes."),
    "VALIDATION_REPORT.md": ("validation", ["human", "automation"], "Generated-output completeness and health report."),
    "EVIDENCE_LEDGER.json": ("evidence-ledger", ["automation", "agent"], "Machine-readable evidence ledger."),
    "CONTEXT_MANIFEST.json": ("manifest", ["automation", "agent"], "Machine-readable manifest for the output bundle."),
    "RUN_STATE.json": ("run-state", ["automation"], "Machine-readable run metadata and compatibility state."),
}


def _manifest_file_entry(name: str) -> dict[str, object]:
    role, audience, purpose = _MANIFEST_FILE_PURPOSES.get(
        name, ("generated-output", ["human", "agent"], "Generated context output.")
    )
    media_type = "application/json" if name.endswith(".json") else "text/markdown"
    if name.endswith(".mmd"):
        media_type = "text/vnd.mermaid"
    return {
        "path": name,
        "role": role,
        "audience": audience,
        "media_type": media_type,
        "purpose": purpose,
    }


def render_context_manifest(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    written_files: list[str],
    errors: list[str],
    generated_at: str | None = None,
) -> RenderResult:
    """Render a machine-readable manifest describing the generated context bundle."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "CONTEXT_MANIFEST.json"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()
    names = [Path(w).name for w in written_files]
    all_names = names + ["CONTEXT_MANIFEST.json", "RUN_STATE.json"]
    deduped_names = list(dict.fromkeys(all_names))

    ss = analysis.scan_summary
    warnings = analysis.evidence_set.warnings()
    manifest = {
        "schema_version": "1.0",
        "schema_mode": "additive",
        "generated_by": f"context-crafter-mcp v{__version__}",
        "generated_at": timestamp,
        "repo_path": repo_path,
        "project_types": detect.project_types,
        "profile": analysis.profile,
        "recommended_start": {
            "agent": "AGENT_BRIEF.md",
            "human": "PROJECT_OVERVIEW.md",
            "navigation": "AI_CONTEXT_INDEX.md",
            "automation": "RUN_STATE.json",
        },
        "files": [_manifest_file_entry(name) for name in deduped_names],
        "scan_summary": {
            "files_scanned": ss.files_scanned,
            "dirs_scanned": ss.dirs_scanned,
            "files_skipped": ss.files_skipped,
            "dirs_skipped": ss.dirs_skipped,
            "budget_exhausted": ss.budget_exhausted,
            "skipped_reasons": ss.skipped_reasons,
            "category_counts": ss.category_counts,
        },
        "evidence_counts": {
            "observed": len(analysis.evidence_set.by_kind(EvidenceKind.OBSERVED)),
            "inferred": len(analysis.evidence_set.by_kind(EvidenceKind.INFERRED)),
            "unknown": len(analysis.evidence_set.by_kind(EvidenceKind.UNKNOWN)),
            "unsupported": len(analysis.evidence_set.by_kind(EvidenceKind.UNSUPPORTED)),
            "error": len(analysis.evidence_set.by_kind(EvidenceKind.ERROR)),
        },
        "warnings_count": len(warnings),
        "errors_count": len(errors),
        "bounded_scan": ss.budget_exhausted or sum(ss.skipped_reasons.values()) > 0,
    }

    write_redacted_text(path, json.dumps(manifest, indent=2))
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=ss.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=ss,
    )


def render_evidence_ledger(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    generated_at: str | None = None,
) -> RenderResult:
    """Render machine-readable evidence details for generated claims."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "EVIDENCE_LEDGER.json"

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()
    analysis_items = analysis.evidence_set.items
    detect_items = detect.evidence_set.items
    all_items = analysis_items + detect_items
    counts_by_kind = {kind.value: len([e for e in all_items if e.kind == kind]) for kind in EvidenceKind}
    counts_by_confidence = {
        confidence: len([e for e in all_items if e.confidence.value == confidence])
        for confidence in ("high", "medium", "low")
    }
    analyzer_counts: dict[str, int] = {}
    for item in all_items:
        analyzer = item.analyzer or "unknown"
        analyzer_counts[analyzer] = analyzer_counts.get(analyzer, 0) + 1

    ledger = {
        "schema_version": "1.0",
        "schema_mode": "additive",
        "generated_by": f"context-crafter-mcp v{__version__}",
        "generated_at": timestamp,
        "repo_path": repo_path,
        "project_types": detect.project_types,
        "profile": analysis.profile,
        "summary": {
            "total": len(all_items),
            "counts_by_kind": counts_by_kind,
            "counts_by_confidence": counts_by_confidence,
            "counts_by_analyzer": dict(sorted(analyzer_counts.items())),
            "warnings_count": len([e for e in all_items if e.kind in (EvidenceKind.UNKNOWN, EvidenceKind.UNSUPPORTED)]),
            "errors_count": len([e for e in all_items if e.kind == EvidenceKind.ERROR]),
        },
        "items": [{**item.to_dict(), "phase": "analysis"} for item in analysis_items]
        + [{**item.to_dict(), "phase": "detection"} for item in detect_items],
    }

    write_redacted_text(path, json.dumps(ledger, indent=2))
    ss = analysis.scan_summary
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=ss.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=ss,
    )
