"""Markdown renderer for repo documentation."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from context_crafter_mcp import __version__
from context_crafter_mcp.filesystem import safe_output_path
from context_crafter_mcp.models import (
    AnalysisResult,
    DetectResult,
    EvidenceKind,
    NodePackage,
    RenderResult,
    get_profile_limit,
)

GENERATED_HEADER = (
    f"<!-- GENERATED by context-crafter-mcp v{__version__}. "
    "Do not edit manually unless you intend to overwrite generated output. -->\n"
)


def _join(items: list[str]) -> str:
    if not items:
        return "_None found_"
    return "\n".join(f"- {i}" for i in items)


def _is_test_or_temp(rel_path: str) -> bool:
    """Check if a file is likely a test or temp/debug script."""
    lower = rel_path.lower()
    parts = Path(lower).parts
    if any(p.startswith("test") for p in parts):
        return True
    if any(p in ("tests", "testing", "debug") for p in parts):
        return True
    name = Path(lower).name
    if name.startswith("debug_") or name.startswith("temp_") or name.startswith("tmp_"):
        return True
    return False


def _make_anchor(text: str) -> str:
    """Convert a heading text to a markdown anchor."""
    return text.lower().strip().replace(" ", "-").replace("/", "").replace(".", "").replace("(", "").replace(")", "")


def _toc_for_headings(headings: list[str]) -> list[str]:
    """Generate a simple markdown TOC from heading texts."""
    lines = ["## Table of Contents", ""]
    for h in headings:
        lines.append(f"- [{h}](#{_make_anchor(h)})")
    lines.append("")
    return lines


def _is_compact_eligible(analysis: AnalysisResult) -> bool:
    """True when compact profile omits optional sections."""
    return analysis.profile == "compact"


def _maybe_errors_section(analysis: AnalysisResult) -> list[str]:
    if not analysis.errors:
        return []
    lines = [
        "## Errors",
        "",
        "The following non-fatal errors were encountered during analysis:",
        "",
    ]
    for err in analysis.errors[:30]:
        lines.append(f"- {err}")
    lines.append("")
    return lines


def _render_evidence_section(analysis: AnalysisResult, profile: str) -> list[str]:
    """Render an Evidence section from the analysis evidence set."""
    ev = analysis.evidence_set
    if not ev:
        return []
    lines: list[str] = ["## Evidence", ""]
    observed = ev.by_kind(EvidenceKind.OBSERVED)
    inferred = ev.by_kind(EvidenceKind.INFERRED)
    unknowns = ev.by_kind(EvidenceKind.UNKNOWN)
    unsupported = ev.by_kind(EvidenceKind.UNSUPPORTED)
    errors = ev.by_kind(EvidenceKind.ERROR)

    if observed:
        lines.append("### Observed")
        for e in observed[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    if inferred:
        lines.append("### Inferred")
        for e in inferred[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    if unknowns:
        lines.append("### Unknown")
        for e in unknowns[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    if unsupported:
        lines.append("### Unsupported")
        for e in unsupported[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    if errors:
        lines.append("### Errors")
        for e in errors[: get_profile_limit(profile, "abstractions")]:
            lines.append(f"- {e.message}")
        lines.append("")
    return lines


def render_project_overview(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate PROJECT_OVERVIEW.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "PROJECT_OVERVIEW.md"

    headings = [
        "Project Metadata",
        "Root Files",
        "Source Layout",
        "Entry Points",
        "Dependencies",
    ]

    lines: list[str] = [
        GENERATED_HEADER,
        f"# Project Overview: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Detected types**: {', '.join(detect.project_types)}",
        f"- **Evidence**: {', '.join(f'{k} ({v})' for k, v in detect.evidence.items())}",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        "",
    ]

    has_langs = any(
        [
            analysis.python_modules,
            analysis.node_packages,
            analysis.dotnet_projects,
            analysis.rust_crates,
            analysis.go_modules,
            analysis.java_projects,
        ]
    )
    compact_eligible = _is_compact_eligible(analysis)
    if has_langs and not (compact_eligible and len(analysis.project_types) <= 1):
        headings.insert(4, "Language Summaries")

    # Add evidence heading if there is evidence and profile is not compact on tiny repo
    if analysis.evidence_set and not compact_eligible:
        headings.insert(1, "Evidence")

    lines += _toc_for_headings(headings)

    # Metadata section
    meta = analysis.metadata
    lines += [
        "## Project Metadata",
        "",
    ]
    if meta.name:
        lines.append(f"- **Name**: {meta.name}")
    if meta.description:
        lines.append(f"- **Description**: {meta.description}")
    if meta.version:
        lines.append(f"- **Version**: {meta.version}")
    if meta.license:
        lines.append(f"- **License**: {meta.license}")
    if meta.authors:
        lines.append(f"- **Authors**: {', '.join(meta.authors)}")
    if meta.homepage:
        lines.append(f"- **Homepage**: {meta.homepage}")
    if meta.repository:
        lines.append(f"- **Repository**: {meta.repository}")
    if meta.keywords:
        lines.append(f"- **Keywords**: {', '.join(meta.keywords)}")
    if not any([meta.name, meta.description, meta.version, meta.license, meta.authors]):
        lines.append("_No project metadata found in config files._")
    lines.append("")

    if analysis.evidence_set and not compact_eligible:
        lines += _render_evidence_section(analysis, analysis.profile)

    lines += [
        "## Root Files",
        "",
        _join(analysis.root_files[: get_profile_limit(analysis.profile, "root_files")]),
        "",
        "## Source Layout",
        "",
    ]

    # Show more detailed source layout for Python
    if analysis.python_modules:
        # Build a module tree
        source_modules = [m for m in analysis.python_modules if not _is_test_or_temp(m.rel_path)]
        pkg_tree: dict[str, list[str]] = {}
        for m in source_modules:
            parts = Path(m.rel_path).parts
            if len(parts) >= 2:
                pkg = parts[0]
                sub = "/".join(parts[1:])
            else:
                pkg = "root"
                sub = m.rel_path
            pkg_tree.setdefault(pkg, []).append(sub)

        limit = get_profile_limit(analysis.profile, "python_modules_display")
        for pkg_name, files in sorted(pkg_tree.items()):
            lines.append(f"- `{pkg_name}/` ({len(files)} files)")
            for f in sorted(files)[:limit]:
                lines.append(f"  - `{f}`")
            if len(files) > limit:
                lines.append(f"  - ... and {len(files) - limit} more")
            lines.append("")
    else:
        lines += _join(analysis.source_directories[: get_profile_limit(analysis.profile, "source_dirs")])
        lines.append("")

    lines += [
        "## Entry Points",
        "",
        _join(analysis.likely_entry_points[: get_profile_limit(analysis.profile, "entry_points")]),
        "",
    ]

    # Dependencies section
    lines += [
        "## Dependencies",
        "",
    ]
    if analysis.python_dependencies:
        lines.append("### Runtime")
        for dep in analysis.python_dependencies[: get_profile_limit(analysis.profile, "deps")]:
            lines.append(f"- {dep}")
        lines.append("")
    if analysis.python_dev_dependencies:
        lines.append("### Development")
        for dep in analysis.python_dev_dependencies[: get_profile_limit(analysis.profile, "dev_deps")]:
            lines.append(f"- {dep}")
        lines.append("")
    if not analysis.python_dependencies and not analysis.python_dev_dependencies:
        if analysis.node_packages and analysis.node_packages[0].dependencies:
            node_pkg: NodePackage = analysis.node_packages[0]
            for dep in node_pkg.dependencies[: get_profile_limit(analysis.profile, "deps")]:
                lines.append(f"- {dep}")
            lines.append("")
        elif analysis.rust_crates and analysis.rust_crates[0].dependencies:
            for dep in analysis.rust_crates[0].dependencies[: get_profile_limit(analysis.profile, "deps")]:
                lines.append(f"- {dep}")
            lines.append("")
        elif analysis.go_modules and analysis.go_modules[0].dependencies:
            for dep in analysis.go_modules[0].dependencies[: get_profile_limit(analysis.profile, "deps")]:
                lines.append(f"- {dep}")
            lines.append("")
        elif analysis.java_projects and analysis.java_projects[0].dependencies:
            for dep in analysis.java_projects[0].dependencies[: get_profile_limit(analysis.profile, "deps")]:
                lines.append(f"- {dep}")
            lines.append("")
        else:
            lines.append("_No dependencies identified._")
            lines.append("")

    lines += [
        "",
    ]

    if analysis.python_modules:
        lines += [
            "### Python Summary",
            "",
            f"Modules scanned: {len(analysis.python_modules)}",
            "",
        ]
        entry_mods = [m for m in analysis.python_modules if m.is_entry_point][
            : get_profile_limit(analysis.profile, "python_modules_display")
        ]
        if entry_mods:
            lines += ["#### Likely Python Entry Points", ""]
            for m in entry_mods:
                lines.append(f"- `{m.rel_path}`")
            lines.append("")
        classes: list[str] = []
        funcs: list[str] = []
        for m in analysis.python_modules:
            for c in m.classes:
                classes.append(f"{m.rel_path}::{c}")
            for f in m.functions:
                funcs.append(f"{m.rel_path}::{f}")
        lines += [f"Classes: {len(classes)}", f"Functions: {len(funcs)}", ""]

    if analysis.node_packages:
        node_pkg2: NodePackage = analysis.node_packages[0]
        lines += ["### Node/JS Summary", ""]
        if node_pkg2.name:
            lines.append(f"Package: `{node_pkg2.name}`")
        if node_pkg2.scripts:
            lines += ["#### Scripts", ""]
            for k, v in list(node_pkg2.scripts.items())[
                : get_profile_limit(analysis.profile, "python_modules_display")
            ]:
                lines.append(f"- `{k}`: `{v}`")
            lines.append("")
        lines.append(f"JS/TS files: {len(node_pkg2.files)}")
        if node_pkg2.classes:
            lines.append(f"Classes: {len(node_pkg2.classes)}")
        if node_pkg2.functions:
            lines.append(f"Functions: {len(node_pkg2.functions)}")
        if node_pkg2.exports:
            lines.append(f"Exports: {len(node_pkg2.exports)}")
        lines.append("")

    if analysis.dotnet_projects:
        lines += ["### .NET Summary", ""]
        for sol in analysis.dotnet_solutions:
            lines.append(f"- Solution: `{sol.name}` ({sol.rel_path})")
        for proj in analysis.dotnet_projects[: get_profile_limit(analysis.profile, "python_modules_display")]:
            lines.append(f"- Project: `{proj.name}` ({proj.rel_path})")
            if proj.target_frameworks:
                lines.append(f"  - Targets: {', '.join(proj.target_frameworks)}")
            if proj.output_type:
                lines.append(f"  - Output: {proj.output_type}")
            if proj.classes:
                lines.append(f"  - Classes: {len(proj.classes)}")
        lines.append("")

    if analysis.rust_crates:
        crate = analysis.rust_crates[0]
        lines += ["### Rust Summary", ""]
        if crate.name:
            lines.append(f"Crate: `{crate.name}`")
        lines.append(f"Modules: {len(crate.modules)}")
        if crate.traits:
            lines.append(f"Traits: {len(crate.traits)}")
        if crate.impls:
            lines.append(f"Impls: {len(crate.impls)}")
        if crate.entry_points:
            lines += ["#### Entry Points", ""]
            for ep in crate.entry_points:
                lines.append(f"- `{ep}`")
            lines.append("")
        if crate.dependencies:
            lines += ["#### Dependencies", ""]
            for dep in crate.dependencies[: get_profile_limit(analysis.profile, "deps")]:
                lines.append(f"- {dep}")
            lines.append("")

    if analysis.go_modules:
        mod = analysis.go_modules[0]
        lines += ["### Go Summary", ""]
        if mod.name:
            lines.append(f"Module: `{mod.name}`")
        lines.append(f"Packages: {len(mod.packages)}")
        if mod.structs:
            lines.append(f"Structs: {len(mod.structs)}")
        if mod.interfaces:
            lines.append(f"Interfaces: {len(mod.interfaces)}")
        if mod.entry_points:
            lines += ["#### Entry Points", ""]
            for ep in mod.entry_points:
                lines.append(f"- `{ep}`")
            lines.append("")
        if mod.dependencies:
            lines += ["#### Dependencies", ""]
            for dep in mod.dependencies[: get_profile_limit(analysis.profile, "deps")]:
                lines.append(f"- {dep}")
            lines.append("")

    if analysis.java_projects:
        java_proj = analysis.java_projects[0]
        lines += ["### Java Summary", ""]
        if java_proj.name:
            lines.append(f"Project: `{java_proj.name}`")
        if java_proj.build_tool:
            lines.append(f"Build tool: `{java_proj.build_tool}`")
        lines.append(f"Classes: {len(java_proj.classes)}")
        if java_proj.methods:
            lines.append(f"Methods: {len(java_proj.methods)}")
        if java_proj.annotations:
            lines.append(f"Annotations: {len(java_proj.annotations)}")
        if java_proj.entry_points:
            lines += ["#### Entry Points", ""]
            for ep in java_proj.entry_points:
                lines.append(f"- `{ep}`")
            lines.append("")
        if java_proj.dependencies:
            lines += ["#### Dependencies", ""]
            for dep in java_proj.dependencies[: get_profile_limit(analysis.profile, "deps")]:
                lines.append(f"- {dep}")
            lines.append("")

    lines += _maybe_errors_section(analysis)
    if not compact_eligible:
        lines += [
            "## Generic Notes",
            "",
            f"- Test directories: {', '.join(analysis.test_directories[:10]) or 'None identified'}",
            f"- Docs files: {len(analysis.docs_files)}",
            f"- Config files: {len(analysis.config_files)}",
            "",
        ]
    lines += [
        "---",
        "*This file was generated by context-crafter-mcp and may be regenerated.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )


def render_repo_map(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate REPO_MAP.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "REPO_MAP.md"

    lines: list[str] = [
        GENERATED_HEADER,
        f"# Repository Map: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Directory Tree",
        "",
        "```",
    ]
    lines += analysis.directory_tree[: get_profile_limit(analysis.profile, "tree_max_lines")]
    lines += [
        "```",
        "",
        "## Important Config Files",
        "",
        _join(analysis.config_files[: get_profile_limit(analysis.profile, "config_files")]),
        "",
        "## Likely Entry Points",
        "",
        _join(analysis.likely_entry_points[: get_profile_limit(analysis.profile, "entry_points")]),
        "",
        "## Test Directories",
        "",
        _join(analysis.test_directories[: get_profile_limit(analysis.profile, "test_dirs")]),
        "",
        "## Docs Directories",
        "",
        _join(analysis.docs_files[: get_profile_limit(analysis.profile, "docs_files")]),
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )


def _extract_architecture_notes(analysis: AnalysisResult) -> dict[str, list[str]]:
    """Extract architecture patterns and notes from the analysis."""
    notes: dict[str, list[str]] = {
        "patterns": [],
        "abstractions": [],
        "module_relationships": [],
        "concerns": [],
    }

    # Python-specific architecture analysis
    if analysis.python_modules:
        source_modules = [m for m in analysis.python_modules if not _is_test_or_temp(m.rel_path)]

        # Detect plugin/registry pattern
        registry_modules = [
            m for m in source_modules if "registry" in m.rel_path.lower() or "register" in " ".join(m.functions)
        ]
        if registry_modules:
            notes["patterns"].append("Plugin/Registry pattern detected (dynamic analyzer registration).")

        # Detect pipeline/orchestration pattern
        pipeline_modules = [
            m
            for m in source_modules
            if any(p in m.rel_path.lower() for p in ["graph", "pipeline", "workflow", "orchestr"])
        ]
        if pipeline_modules:
            notes["patterns"].append("Pipeline/Orchestration pattern detected (state-machine or graph-based flow).")

        # Detect server/API pattern
        server_modules = [m for m in source_modules if "server" in m.rel_path.lower()]
        if server_modules:
            notes["patterns"].append("Server/API pattern detected (MCP stdio server or similar).")

        # Count key abstractions
        all_classes: list[str] = []
        all_async_funcs: list[str] = []
        for m in source_modules:
            for c in m.classes:
                all_classes.append(f"{m.rel_path}::{c}")
            for f in m.async_functions:
                all_async_funcs.append(f"{m.rel_path}::{f}")

        if all_classes:
            notes["abstractions"].append(f"{len(all_classes)} class(es) defined across source modules.")
            for c in all_classes[: get_profile_limit(analysis.profile, "abstractions")]:
                notes["abstractions"].append(f"  - `{c}`")
            if len(all_classes) > 10:
                notes["abstractions"].append(f"  - ... and {len(all_classes) - 10} more")

        if all_async_funcs:
            notes["abstractions"].append(
                f"{len(all_async_funcs)} async function(s) — likely I/O-bound or event-driven architecture."
            )

        # Module relationships
        internal_edges: set[tuple[str, str]] = set()
        for m in source_modules:
            raw_src = m.module_name or Path(m.rel_path).parts[0] if Path(m.rel_path).parts else ""
            # Strip src/ prefixes
            for prefix in ("src.", "lib.", "source.", "sources."):
                if raw_src.startswith(prefix):
                    raw_src = raw_src[len(prefix) :]
            src_pkg = raw_src.split(".")[0] if raw_src else ""
            for imp in m.internal_imports:
                first = imp.split(".")[0]
                if first and first != src_pkg:
                    internal_edges.add((src_pkg, first))

        if internal_edges:
            notes["module_relationships"].append("Cross-module dependencies detected:")
            for src, tgt in sorted(internal_edges)[: get_profile_limit(analysis.profile, "internal_edges")]:
                notes["module_relationships"].append(f"  - `{src}` → `{tgt}`")
            if len(internal_edges) > get_profile_limit(analysis.profile, "internal_edges"):
                notes["module_relationships"].append(f"  - ... and {len(internal_edges) - 15} more")

        # Cyclic dependency check (simple)
        cycles: list[str] = []
        for src, tgt in internal_edges:
            if (tgt, src) in internal_edges:
                cycle = f"`{src}` ↔ `{tgt}`"
                if cycle not in cycles:
                    cycles.append(cycle)
        if cycles:
            notes["concerns"].append("Potential bidirectional/cyclic dependencies detected:")
            for c in cycles[: get_profile_limit(analysis.profile, "cycles")]:
                notes["concerns"].append(f"  - {c}")

        # Large modules
        large_modules = [m for m in source_modules if len(m.classes) > 10 or len(m.functions) > 20]
        if large_modules:
            notes["concerns"].append("Large modules (high class/function count) — consider decomposition:")
            for m in large_modules[: get_profile_limit(analysis.profile, "large_modules")]:
                notes["concerns"].append(f"  - `{m.rel_path}` ({len(m.classes)} classes, {len(m.functions)} functions)")

    # Go-specific patterns
    if analysis.go_modules:
        mod = analysis.go_modules[0]
        if mod.interfaces and len(mod.interfaces) > 3:
            notes["patterns"].append("Interface-heavy design (Go idiomatic polymorphism).")
        if mod.entry_points:
            notes["patterns"].append("CLI/service architecture detected (main package entry points).")

    # Java-specific patterns
    if analysis.java_projects:
        java_proj = analysis.java_projects[0]
        spring_annotations = {"Component", "Service", "Controller", "Repository", "Entity", "SpringBootApplication"}
        found_spring = spring_annotations & set(java_proj.annotations)
        if found_spring:
            notes["patterns"].append(f"Spring framework detected ({', '.join(sorted(found_spring))}).")
        if len(java_proj.classes) > 20:
            notes["abstractions"].append(f"{len(java_proj.classes)} class(es) — class-heavy architecture.")

    # Node-specific patterns
    if analysis.node_packages:
        node_pkg = analysis.node_packages[0]
        web_frameworks = {"express", "fastify", "koa", "hapi", "nest"}
        frontend_frameworks = {"react", "vue", "angular", "svelte", "next"}
        all_deps = set(node_pkg.dependencies) | set(node_pkg.dev_dependencies)
        found_web = web_frameworks & all_deps
        found_fe = frontend_frameworks & all_deps
        if found_web:
            notes["patterns"].append(f"Web server framework detected ({', '.join(sorted(found_web))}).")
        if found_fe:
            notes["patterns"].append(f"Frontend framework detected ({', '.join(sorted(found_fe))}).")

    # Rust-specific patterns
    if analysis.rust_crates:
        crate = analysis.rust_crates[0]
        if crate.traits and len(crate.traits) > 2:
            notes["patterns"].append("Trait-based polymorphism detected.")
        if any("tokio" in d for d in crate.dependencies):
            notes["patterns"].append("Async runtime detected (tokio).")

    return notes


def render_architecture_summary(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate ARCHITECTURE_SUMMARY.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "ARCHITECTURE_SUMMARY.md"

    arch_notes = _extract_architecture_notes(analysis)
    has_patterns = any(arch_notes.values())
    compact_eligible = _is_compact_eligible(analysis)

    headings: list[str] = [
        "Detected Stacks",
        "Major Source Directories",
        "Likely Runtime Entry Points",
        "Testing Layout",
        "Packaging / Build System",
        "Documentation State",
    ]
    if arch_notes["patterns"] or not compact_eligible:
        headings.append("Architecture Patterns")
    if arch_notes["abstractions"] or not compact_eligible:
        headings.append("Key Abstractions")
    if arch_notes["module_relationships"] or not compact_eligible:
        headings.append("Module Relationships")
    headings.append("Risks / Unknowns")

    if analysis.errors:
        headings.insert(0, "Errors")

    lines: list[str] = [
        GENERATED_HEADER,
        f"# Architecture Summary: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        "",
    ]

    lines += _toc_for_headings(headings)
    lines += _maybe_errors_section(analysis)

    lines += [
        "## Detected Stacks",
        "",
        _join(detect.project_types),
        "",
        "## Major Source Directories",
        "",
        _join(analysis.source_directories[: get_profile_limit(analysis.profile, "source_dirs")]),
        "",
        "## Likely Runtime Entry Points",
        "",
        _join(analysis.likely_entry_points[: get_profile_limit(analysis.profile, "entry_points")]),
        "",
        "## Testing Layout",
        "",
        _join(analysis.test_directories[: get_profile_limit(analysis.profile, "test_dirs")]),
        "",
        "## Packaging / Build System",
        "",
    ]

    if "python" in detect.project_types:
        lines.append("- Python project detected (look for `pyproject.toml`, `setup.py`)")
    if "node" in detect.project_types:
        lines.append("- Node project detected (look for `package.json`, build scripts)")
    if "dotnet" in detect.project_types:
        lines.append("- .NET project detected (look for `.sln`, `.csproj`)")
    if "rust" in detect.project_types:
        lines.append("- Rust project detected (look for `Cargo.toml`)")
    if "go" in detect.project_types:
        lines.append("- Go project detected (look for `go.mod`)")
    if "java" in detect.project_types:
        lines.append("- Java project detected (look for `pom.xml`, `build.gradle`)")
    lines.append("")

    lines += [
        "## Documentation State",
        "",
        f"- README: {'Yes' if any('readme' in f.lower() for f in analysis.root_files) else 'Not obvious'}",
        f"- Docs files: {len(analysis.docs_files)}",
        "",
    ]

    if arch_notes["patterns"] or not compact_eligible:
        lines += [
            "## Architecture Patterns",
            "",
        ]
        if arch_notes["patterns"]:
            for note in arch_notes["patterns"]:
                lines.append(f"- {note}")
        else:
            lines.append("_No specific architectural patterns identified._")
        lines.append("")

    if arch_notes["abstractions"] or not compact_eligible:
        lines += [
            "## Key Abstractions",
            "",
        ]
        if arch_notes["abstractions"]:
            for note in arch_notes["abstractions"]:
                lines.append(f"- {note}")
        else:
            lines.append("_No significant abstractions identified._")
        lines.append("")

    if arch_notes["module_relationships"] or not compact_eligible:
        lines += [
            "## Module Relationships",
            "",
        ]
        if arch_notes["module_relationships"]:
            for note in arch_notes["module_relationships"]:
                lines.append(note)
        else:
            lines.append("_No cross-module relationships identified._")
        lines.append("")

    lines += [
        "## Risks / Unknowns",
        "",
    ]

    if arch_notes["concerns"]:
        for note in arch_notes["concerns"]:
            lines.append(f"- {note}")

    if not analysis.likely_entry_points:
        lines.append("- No clear entry points were identified automatically.")
    if not analysis.test_directories:
        lines.append("- No test directories were identified automatically.")
    if not analysis.config_files:
        lines.append("- No obvious config files found.")
    if len(analysis.root_files) < 3:
        lines.append("- Repository root appears sparse; may be a monorepo subdirectory or incomplete checkout.")
    if analysis.errors:
        lines.append("- Some files could not be parsed; see analysis errors.")
    if not has_patterns and not any(
        [
            "python" in detect.project_types,
            "node" in detect.project_types,
            "dotnet" in detect.project_types,
            "rust" in detect.project_types,
            "go" in detect.project_types,
            "java" in detect.project_types,
        ]
    ):
        lines.append("- No mainstream stack markers found; architecture inference is limited.")
    if not arch_notes["concerns"] and analysis.likely_entry_points and analysis.test_directories:
        lines.append("- No obvious architectural concerns detected from static analysis.")

    lines += [
        "",
        "---",
        "*This analysis is based purely on static inspection. It may miss runtime architecture or cloud infra.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )


def render_ai_context_index(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate AI_CONTEXT_INDEX.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "AI_CONTEXT_INDEX.md"

    lines: list[str] = [
        GENERATED_HEADER,
        f"# AI Context Index: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        f"- **Detected types**: {', '.join(detect.project_types)}",
        "",
        "## Generated Files",
        "",
        "| File | Purpose |",
        "|------|---------|",
        "| `AI_CONTEXT_INDEX.md` | This index |",
        "| `PROJECT_OVERVIEW.md` | Project metadata, stacks, entry points |",
        "| `REPO_MAP.md` | Directory tree and key files |",
        "| `DEPENDENCY_GRAPH.md` | Mermaid dependency graph |",
        "| `ARCHITECTURE_SUMMARY.md` | Architecture patterns and risks |",
        "| `AGENT_BRIEF.md` | Concise agent-ready summary |",
        "| `VALIDATION_REPORT.md` | Output validation status |",
        "| `SCAN_REPORT.md` | Scan coverage and skipped items |",
        "",
        "## Quick Navigation",
        "",
        "- [Project Overview](PROJECT_OVERVIEW.md)",
        "- [Repository Map](REPO_MAP.md)",
        "- [Dependency Graph](DEPENDENCY_GRAPH.md)",
        "- [Architecture Summary](ARCHITECTURE_SUMMARY.md)",
        "- [Agent Brief](AGENT_BRIEF.md)",
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )


def render_agent_brief(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate AGENT_BRIEF.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "AGENT_BRIEF.md"

    compact_eligible = _is_compact_eligible(analysis)

    lines: list[str] = [
        GENERATED_HEADER,
        f"# Agent Brief: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        f"- **Types**: {', '.join(detect.project_types)}",
        "",
        "## What this is",
        "",
        "Compact, source-grounded context for AI coding agents.",
        "",
        "## Entry points",
        "",
        _join(analysis.likely_entry_points[: get_profile_limit(analysis.profile, "entry_points")]),
        "",
    ]

    if analysis.source_directories or not compact_eligible:
        lines += [
            "## Source layout",
            "",
            _join(analysis.source_directories[: get_profile_limit(analysis.profile, "source_dirs")]),
            "",
        ]

    if analysis.test_directories or not compact_eligible:
        lines += [
            "## Test layout",
            "",
            _join(analysis.test_directories[: get_profile_limit(analysis.profile, "test_dirs")]),
            "",
        ]

    lines += [
        "## Key dependencies",
        "",
    ]
    deps: list[str] = []
    if analysis.python_dependencies:
        deps.extend(analysis.python_dependencies[: get_profile_limit(analysis.profile, "deps")])
    elif analysis.node_packages and analysis.node_packages[0].dependencies:
        deps.extend(analysis.node_packages[0].dependencies[: get_profile_limit(analysis.profile, "deps")])
    elif analysis.rust_crates and analysis.rust_crates[0].dependencies:
        deps.extend(analysis.rust_crates[0].dependencies[: get_profile_limit(analysis.profile, "deps")])
    elif analysis.go_modules and analysis.go_modules[0].dependencies:
        deps.extend(analysis.go_modules[0].dependencies[: get_profile_limit(analysis.profile, "deps")])
    elif analysis.java_projects and analysis.java_projects[0].dependencies:
        deps.extend(analysis.java_projects[0].dependencies[: get_profile_limit(analysis.profile, "deps")])
    lines.append(_join(deps))
    lines.append("")
    lines += [
        "## Warnings",
        "",
    ]
    if analysis.errors:
        lines.append(f"- {len(analysis.errors)} analysis error(s); see full reports.")
    else:
        lines.append("- None.")
    lines.append("")

    # Evidence/unknowns for agent brief
    unknowns = analysis.evidence_set.by_kind(EvidenceKind.UNKNOWN)
    unsupported = analysis.evidence_set.by_kind(EvidenceKind.UNSUPPORTED)
    if unknowns or unsupported:
        lines += [
            "## Unknowns / Limitations",
            "",
        ]
        for e in unknowns[:5]:
            lines.append(f"- {e.message}")
        for e in unsupported[:5]:
            lines.append(f"- {e.message}")
        lines.append("")

    lines += [
        "---",
        "*Generated by context-crafter-mcp. Use PROJECT_OVERVIEW.md and ARCHITECTURE_SUMMARY.md for deeper detail.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )


def render_validation_report(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    written_files: list[str] | None = None,
) -> RenderResult:
    """Generate VALIDATION_REPORT.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "VALIDATION_REPORT.md"

    # Validate the other 7 output files (VALIDATION_REPORT.md is implicitly present)
    required = [
        "AI_CONTEXT_INDEX.md",
        "PROJECT_OVERVIEW.md",
        "REPO_MAP.md",
        "DEPENDENCY_GRAPH.md",
        "ARCHITECTURE_SUMMARY.md",
        "AGENT_BRIEF.md",
        "SCAN_REPORT.md",
    ]
    found: list[str] = []
    missing: list[str] = []
    written_set = {Path(w).name for w in (written_files or [])}
    for name in required:
        if name in written_set or (out / name).exists():
            found.append(name)
        else:
            missing.append(name)

    lines: list[str] = [
        GENERATED_HEADER,
        f"# Validation Report: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Output Files",
        "",
        f"- Found: {len(found)}/{len(required)}",
        "",
        "### Found",
        "",
        _join(found),
        "",
    ]
    if missing:
        lines += [
            "### Missing",
            "",
            _join(missing),
            "",
        ]
    else:
        lines += [
            "### Missing",
            "",
            "_None._",
            "",
        ]

    lines += [
        "## Analysis Health",
        "",
        f"- Files scanned: {analysis.files_scanned}",
        f"- Errors: {len(analysis.errors)}",
        f"- Project types: {', '.join(detect.project_types)}",
        "",
    ]
    if analysis.errors:
        lines += [
            "### Errors",
            "",
        ]
        for err in analysis.errors[:20]:
            lines.append(f"- {err}")
        lines.append("")

    lines += [
        "## Result",
        "",
        "PASS" if not missing else "PARTIAL",
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )


def render_scan_report(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
) -> RenderResult:
    """Generate SCAN_REPORT.md."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "SCAN_REPORT.md"

    lines: list[str] = [
        GENERATED_HEADER,
        f"# Scan Report: {Path(repo_path).resolve().name}",
        "",
        f"- **Path**: `{repo_path}`",
        f"- **Generated**: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Coverage",
        "",
        f"- Files scanned: {analysis.files_scanned}",
        f"- Root files: {len(analysis.root_files)}",
        f"- Source directories: {len(analysis.source_directories)}",
        f"- Test directories: {len(analysis.test_directories)}",
        f"- Config files: {len(analysis.config_files)}",
        f"- Docs files: {len(analysis.docs_files)}",
        "",
        "## Detected stacks",
        "",
        _join(detect.project_types),
        "",
        "## Skipped / Ignored",
        "",
        "- Symlinks: not followed",
        "- Hidden files: excluded by default",
        "- Ignored directories: .git, node_modules, venv, __pycache__, dist, build, target, bin, obj, .next, .turbo, .cache, .mypy_cache, .pytest_cache, .ruff_cache",
        "",
    ]
    if analysis.errors:
        lines += [
            "## Scan errors",
            "",
        ]
        for err in analysis.errors[:30]:
            lines.append(f"- {err}")
        lines.append("")
    else:
        lines += [
            "## Scan errors",
            "",
            "_None._",
            "",
        ]

    lines += [
        "## Safety notes",
        "",
        "- Static analysis only; no code executed.",
        "- No network calls made during generation.",
        "- Output confined to repository root.",
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return RenderResult(
        ok=True,
        written=[str(path)],
        files_scanned=analysis.files_scanned,
        project_types=detect.project_types,
    )
