"""Mermaid diagram renderer."""

from __future__ import annotations

import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from context_crafter_mcp import __version__
from context_crafter_mcp.filesystem import safe_output_path
from context_crafter_mcp.models import AnalysisResult, DetectResult, RenderResult, get_profile_limit
from context_crafter_mcp.redaction import write_redacted_text
from context_crafter_mcp.renderers.markdown import _render_metadata_block

GENERATED_HEADER = (
    f"<!-- GENERATED by context-crafter-mcp v{__version__}. "
    "Do not edit manually unless you intend to overwrite generated output. -->\n"
)


def _sanitize_mermaid_id(name: str) -> str:
    """Sanitize a string for use as a Mermaid node ID."""
    sanitized = "".join(c if c.isalnum() or c in "_-" else "_" for c in name)
    if sanitized and sanitized[0].isdigit():
        sanitized = "_" + sanitized
    if not sanitized:
        sanitized = "_"
    return sanitized[:60]


def _escape_mermaid_label(label: str) -> str:
    """Escape characters that break Mermaid node labels inside quotes."""
    return label.replace('"', "'").replace("[", "(").replace("]", ")")


def _is_test_or_temp(rel_path: str) -> bool:
    """Check if a file is likely a test or temp/debug script."""
    lower = rel_path.lower()
    parts = Path(lower).parts
    if any(p.startswith("test") for p in parts):
        return True
    if any(p in ("tests", "testing", "debug") for p in parts):
        return True
    name = Path(lower).name
    if name.startswith("debug_") or name.startswith("temp_") or name.startswith("tmp_"):
        return True
    return False


# Standard library modules to exclude from external deps
_STDLIB_MODULES = {
    "__future__",
    "abc",
    "argparse",
    "ast",
    "asyncio",
    "base64",
    "bisect",
    "builtins",
    "calendar",
    "collections",
    "contextlib",
    "copy",
    "csv",
    "dataclasses",
    "datetime",
    "decimal",
    "difflib",
    "enum",
    "fnmatch",
    "functools",
    "gc",
    "glob",
    "hashlib",
    "heapq",
    "hmac",
    "html",
    "http",
    "imghdr",
    "inspect",
    "io",
    "itertools",
    "json",
    "keyword",
    "linecache",
    "locale",
    "logging",
    "math",
    "mimetypes",
    "numbers",
    "operator",
    "os",
    "pathlib",
    "pickle",
    "platform",
    "pprint",
    "profile",
    "pstats",
    "queue",
    "random",
    "re",
    "secrets",
    "select",
    "shlex",
    "shutil",
    "signal",
    "socket",
    "sqlite3",
    "statistics",
    "string",
    "struct",
    "subprocess",
    "sys",
    "tarfile",
    "tempfile",
    "textwrap",
    "threading",
    "time",
    "timeit",
    "token",
    "tokenize",
    "traceback",
    "typing",
    "urllib",
    "uuid",
    "venv",
    "warnings",
    "wave",
    "weakref",
    "xml",
    "xmlrpc",
    "zipfile",
    "zipimport",
    "zlib",
    "zoneinfo",
    "tomllib",
    "types",
    "inspect",
    "contextvars",
    "fractions",
}


def _normalize_module_name(module_name: str) -> str:
    """Strip common source-layout prefixes like src., lib. from module names."""
    prefixes = ("src.", "lib.", "source.", "sources.")
    for prefix in prefixes:
        if module_name.startswith(prefix):
            return module_name[len(prefix) :]
    return module_name


def _build_python_package_graph(analysis: AnalysisResult) -> tuple[set[str], set[tuple[str, str]], set[str]]:
    """Build a package-level graph from Python modules."""
    if not analysis.python_modules:
        return set(), set(), set()

    # Filter to source modules only
    source_modules = [m for m in analysis.python_modules if not _is_test_or_temp(m.rel_path)]

    # Collect package nodes and edges
    packages: set[str] = set()
    package_edges: set[tuple[str, str]] = set()
    external_deps: set[str] = set()

    for mod in source_modules:
        # Determine the module's package (strip src/ prefixes)
        raw_name = mod.module_name or (Path(mod.rel_path).parts[0] if Path(mod.rel_path).parts else "unknown")
        norm_name = _normalize_module_name(raw_name)
        parts = norm_name.split(".")
        if len(parts) >= 2:
            pkg = ".".join(parts[:2])  # e.g., context_crafter_mcp.analyzers
        else:
            pkg = parts[0]

        packages.add(pkg)

        for imp in mod.internal_imports:
            norm_imp = _normalize_module_name(imp)
            imp_parts = norm_imp.split(".")
            if len(imp_parts) >= 2:
                target_pkg = ".".join(imp_parts[:2])
            else:
                target_pkg = imp_parts[0]
            if target_pkg != pkg:
                package_edges.add((pkg, target_pkg))

        for imp in mod.imports:
            if imp not in mod.internal_imports:
                first = imp.split(".")[0]
                if first not in _STDLIB_MODULES:
                    external_deps.add(first)

    return packages, package_edges, external_deps


def render_dependency_graph(
    repo_path: str,
    detect: DetectResult,
    analysis: AnalysisResult,
    output_dir: str,
    generated_at: str | None = None,
) -> RenderResult:
    """Generate Mermaid dependency graph files."""
    out = safe_output_path(Path(repo_path), output_dir)
    out.mkdir(parents=True, exist_ok=True)
    mmd_path = out / "DEPENDENCY_GRAPH.mmd"
    md_path = out / "DEPENDENCY_GRAPH.md"

    lines: list[str] = [
        "graph TD",
    ]
    nodes: set[str] = set()
    edges: set[tuple[str, str]] = set()
    external: set[str] = set()

    # Python package-level graph
    if analysis.python_modules:
        py_packages, py_edges, py_external = _build_python_package_graph(analysis)
        external.update(py_external)

        if py_packages:
            lines.append("    subgraph Internal_Packages[Internal Packages]")
            for pkg in sorted(py_packages):
                pkg_id = _sanitize_mermaid_id(pkg)
                nodes.add(pkg_id)
                lines.append(f'        {pkg_id}["{_escape_mermaid_label(pkg)}"]')
            lines.append("    end")

            for edge in sorted(py_edges):
                src_id = _sanitize_mermaid_id(edge[0])
                tgt_id = _sanitize_mermaid_id(edge[1])
                edges.add((src_id, tgt_id))

    # Node packages and workspace edges
    local_pkg_names = {p.name for p in analysis.node_packages if p.name}
    if analysis.node_packages:
        if len(analysis.node_packages) > 1:
            lines.append("    subgraph NodeWorkspace[Node / TypeScript Workspace]")
        for npkg in analysis.node_packages:
            pkg_label = npkg.name or (Path(npkg.rel_path).parent.name if npkg.rel_path else "unknown")
            pkg_id = _sanitize_mermaid_id(pkg_label)
            if pkg_id not in nodes:
                nodes.add(pkg_id)
                lines.append(f'    {pkg_id}["{_escape_mermaid_label(pkg_label)}"]')
            # Edges from local dependencies
            for dep in npkg.dependencies:
                if dep in local_pkg_names:
                    dep_id = _sanitize_mermaid_id(dep)
                    if dep_id not in nodes:
                        nodes.add(dep_id)
                        lines.append(f'    {dep_id}["{_escape_mermaid_label(dep)}"]')
                    edges.add((pkg_id, dep_id))
            # External deps
            for dep in npkg.dependencies:
                if dep not in local_pkg_names:
                    external.add(dep)
            for dep in npkg.dev_dependencies:
                external.add(dep)
        if len(analysis.node_packages) > 1:
            lines.append("    end")

        # Legacy import edges from first package (keep for backward compatibility)
        if analysis.node_packages[0].import_edges:
            for src, target in analysis.node_packages[0].import_edges:
                src_id = _sanitize_mermaid_id(Path(src).name)
                if target.startswith(".") or "/" in target:
                    tgt_id = _sanitize_mermaid_id(target)
                    if src_id not in nodes:
                        nodes.add(src_id)
                        lines.append(f'    {src_id}["{_escape_mermaid_label(src)}"]')
                    if tgt_id not in nodes:
                        nodes.add(tgt_id)
                        lines.append(f'    {tgt_id}["{_escape_mermaid_label(target)}"]')
                    edges.add((src_id, tgt_id))
                else:
                    external.add(target.split("/")[-1])

    # .NET project references
    if analysis.dotnet_projects:
        for proj in analysis.dotnet_projects:
            proj_id = _sanitize_mermaid_id(proj.name)
            if proj_id not in nodes:
                nodes.add(proj_id)
                lines.append(f'    {proj_id}["{_escape_mermaid_label(proj.name)}"]')
            for ref in proj.project_refs:
                ref_name = Path(ref).stem
                ref_id = _sanitize_mermaid_id(ref_name)
                if ref_id not in nodes:
                    nodes.add(ref_id)
                    lines.append(f'    {ref_id}["{_escape_mermaid_label(ref_name)}"]')
                edges.add((proj_id, ref_id))
        for sol in analysis.dotnet_solutions:
            sol_id = _sanitize_mermaid_id(sol.name)
            if sol_id not in nodes:
                nodes.add(sol_id)
                lines.append(f'    {sol_id}["{_escape_mermaid_label(f"{sol.name} (sln)")}"]')
            for p in sol.projects:
                p_name = Path(p).stem
                p_id = _sanitize_mermaid_id(p_name)
                if p_id not in nodes:
                    nodes.add(p_id)
                    lines.append(f'    {p_id}["{_escape_mermaid_label(p_name)}"]')
                edges.add((sol_id, p_id))

    for edge in edges:
        lines.append(f"    {edge[0]} --> {edge[1]}")

    # External dependencies
    # Prefer pyproject.toml deps over inferred AST imports
    if analysis.python_dependencies:
        external.update(analysis.python_dependencies)
    if analysis.python_dev_dependencies:
        external.update(analysis.python_dev_dependencies)
    if analysis.go_modules:
        external.update(analysis.go_modules[0].dependencies)
    if analysis.java_projects:
        external.update(analysis.java_projects[0].dependencies)
    if analysis.rust_crates:
        external.update(analysis.rust_crates[0].dependencies)

    ext_limit = get_profile_limit(analysis.profile, "mermaid_external")
    if external:
        ext_list = sorted(external)[:ext_limit]
        lines.append("    subgraph External_Deps[External Dependencies]")
        for dep in ext_list:
            dep_id = _sanitize_mermaid_id(dep)
            lines.append(f'        {dep_id}[["{_escape_mermaid_label(dep)}"]]')
        lines.append("    end")

    mmd_content = "\n".join(lines)

    timestamp = generated_at or datetime.now(timezone.utc).isoformat()

    md_lines: list[str] = [
        GENERATED_HEADER,
    ]
    md_lines += _render_metadata_block(repo_path, analysis, timestamp)
    md_lines += [
        f"# Dependency Graph: {Path(repo_path).resolve().name}",
        "",
        "## Graph",
        "",
        "```mermaid",
    ]
    md_lines += lines
    md_lines += [
        "```",
        "",
        "## External Dependencies",
        "",
    ]
    if external:
        for dep in sorted(external)[:ext_limit]:
            md_lines.append(f"- {dep}")
    else:
        md_lines.append("_No external dependencies identified._")
    md_lines += [
        "",
        "---",
        "*Generated by context-crafter-mcp.*",
        "",
    ]

    write_redacted_text(mmd_path, GENERATED_HEADER + mmd_content + "\n")
    write_redacted_text(md_path, "\n".join(md_lines) + "\n")

    written = [str(mmd_path), str(md_path)]

    # Optional: generate PNG/SVG if mmdc is available
    if shutil.which("mmdc"):
        for fmt in ("png", "svg"):
            out_path = out / f"DEPENDENCY_GRAPH.{fmt}"
            try:
                subprocess.run(
                    ["mmdc", "-i", str(mmd_path), "-o", str(out_path), "-b", "transparent"],
                    capture_output=True,
                    timeout=60,
                    check=True,
                )
                written.append(str(out_path))
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
                pass

    return RenderResult(
        ok=True,
        written=written,
        files_scanned=analysis.scan_summary.files_scanned,
        project_types=detect.project_types,
        resolved_output_dir=str(out),
        scan_summary=analysis.scan_summary,
    )
